### ISSUE TITLE
[feature] Reload config on SIGHUP

### ISSUE THREAD

**Issue by tanner-bruce** [kubernetes-sigs/prometheus-adapter#104]
In the interest of not having to recreate the pod every time the config changes, it would be nice to be able to SIGHUP the process, or webhook it, which allows some easy automation ala https://github.com/jimmidyson/configmap-reload

At the same time, it may also be worth adding in prometheus metrics for the adapter, such as a `last_reload_successful` metric to allow easy alerting when a reload fails.

**Comment by igcherkaev** [comment]
yes, indeed, would be very helpfull!
