### ISSUE TITLE
problems on k8s 1.11.3

### ISSUE THREAD

**Issue by ChristofferNicklassonLenswayGroup** [kubernetes-sigs/prometheus-adapter#117]
So after reading all pages.. testing what it seems all things from both pages and  issues here i am stuck.
"kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/custom-metrics/pods/*/http_requests"
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/custom-metrics/pods/%2A/http_requests"},"items":[]}

So i would be happy with some help :)
End goal is to have HBA scaling on RPS.

Thanxs

**Comment by DirectXMan12** [comment]
can you please elaborate a bit more on your setup?  Do you have a pod exposing `http_requests_total`, which is then being collected by Prometheus?

**Comment by ChristofferNicklassonLenswayGroup** [comment]
Hello.
i will do my best to answer any questions:
its a baremetal setup  running 1.12.1  
Dont know if i have that, i where just following the guide can ofc have missed something.

**Comment by DirectXMan12** [comment]
So, nothing in kubernetes provides RPS metrics out of the box.  The guides runs with a pod that specifically exposes that metric.  Can you actually see the metrics in your Prometheus?

**Comment by ChristofferNicklassonLenswayGroup** [comment]
I where under the belief that it would create that.
Would then recommend that its added to the guids how to do that.
