### ISSUE TITLE
[feature] Allow label value interpolation in metric names

### ISSUE THREAD

**Issue by tmatias** [kubernetes-sigs/prometheus-adapter#137]
Some exporters, like the [cloudwatch](https://github.com/prometheus/cloudwatch_exporter) one, expose metrics in a generic way (a common metric name, plus a meaningful label),  where the metric name per se is not meaningful enough to be used effectively (not ideal for consumers, but somewhat common to see in exporters that bridge metrics from existing sources).

Example:

```
aws_sqs_approximate_number_of_messages_visible_average{...,queue_name="one"} 
aws_sqs_approximate_number_of_messages_visible_average{...,queue_name="another"}
```

In this case specifically, we would like to retain per-queue metrics, since having an aggregate over all of them would lose meaning. Doing a 1:1 map to a kubernetes resource won't work since a single pod/deployment/etc can be consuming from more than one queue.

Currently, this can be achieved by writing multiple discovery rules, but it would easier if we could use those labels in figuring out the metric names, something like:

```
name:
  as: '{{.labels.queue_name}}_queue_depth'
```

(not sure we would want to allow full templating capabilities, tough).

**Comment by DirectXMan12** [comment]
the hard part here is that we don't record label values internally -- just label names.  This seems like a good use case for the new label selector support, but it needs to finish landing in the custom-metrics-apiserver boilerplate repo first (kubernetes-incubator/custom-metrics-apiserver#35).

**Comment by Freyert** [comment]
What's the status on this? It seems like [kubernetes-incubator/custom-metrics-apiserver#35](https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/35) is stalled?

**Comment by jtmkrueger** [comment]
> Currently, this can be achieved by writing multiple discovery rules

@tmatias do you have any documentation you can point to that references how this works? I'm currently trying to figure out how to get individual sidekiq queue metrics from [sidekiq-prometheus-exporter](https://github.com/Strech/sidekiq-prometheus-exporter) usable in a horizontal pod autoscaler

**Comment by agolomoodysaada** [comment]
Trying to achieve the same thing with Kafka

**Comment by wanghaokk** [comment]
@DirectXMan12 Hi, When will this feature be supported by k8s-prometheus-adapter?
Prometheus metric labels are meaningful in many cases, especially for HPA.

**Comment by s-urbaniak** [comment]
@tmatias @wanghaokk: @DirectXMan12 is not actively working on this project any more, so I'll chime in as I am actively working on it now. Regarding the requested feature I see two possibilities for now:

1. If your label values are known in forehand and is a fixed set, you could define a recording rule for each label value instance and reference those as custom metrics.
2. Keep on using one metric and specify `metricLabelSelector` as https://github.com/kubernetes/metrics/blob/483643a4d1f8103e9d6c66f0735cdd9fd7542b8a/pkg/apis/custom_metrics/types.go#L87

When it comes to native support in prometheus adapter I am a hesitant to add this as a feature. The reason actually refers to point 1. above. If your label values are known in forehand, you can declare separate recording rules and reference those in the prometheus adapter config.

If your label values are not known in forehand, you effective imply an infinite number of unknown metrics which doesn't sound right and is not idiomatic in the prometheus world.

**Comment by wanghaokk** [comment]
@s-urbaniak Thanks, it seems like one must be certain of which metrics will be exposed by adapter. Unknown label values are not usually used in out monitoring system, so we would adopt method 1. as you mentioned.

**Comment by hugobcar** [comment]
Instead of using cloudwatch-export, take a look at this tool https://github.com/hugobcar/tiamat. This renamed sqs metric names to use with prometheus-adapter
