### ISSUE TITLE
Crash when setting --secure-port=0

### ISSUE THREAD

**Issue by stuartnelson3** [kubernetes-sigs/prometheus-adapter#145]
From reading the commandline documentation, it seems to say that TLS can be disabled by sett4ing `--secure-port=0`:

```
--secure-port int  
  The port on which to serve HTTPS with authentication and authorization.
  If 0, don't serve HTTPS at all. (default 443)
```

However, when I set this flag to 0, it appears to crash on startup:

```
F1207 12:20:47.179578      10 adapter.go:211] unable to run custom metrics adapter: Genericapiserver.New() called with config.LoopbackClientConfig == nil
```

Is this expected, or was I doing something wrong?

I was using v0.4.0.

**Comment by DirectXMan12** [comment]
hmm... Does this only happen with `--secure-port=0`?  I wonder if it's just a weird case in the apiserver library...

**Comment by stuartnelson3** [comment]
Yeah, it only happens when I set `--secure-port=0`. I was trying to force HTTP traffic at the time. It's not blocking my use of the adapter as I'm using https now, but thought it would be worthwhile to report it.

**Comment by stuartnelson3** [comment]
feel free to close

**Comment by cmendesce** [comment]
I was unable to set a different than 6443 in the `secure-port` param when deploy it using istio. I found this issue and tested with `0` param and I got the same error of @stuartnelson3 . I'm using version 0.5.0.
