### ISSUE TITLE
HPA on metric of another pod

### ISSUE THREAD

**Issue by marcin-kasinski** [kubernetes-sigs/prometheus-adapter#149]
Hello.

Is there any chance to use HPA based on metric from another pod.

In my environment I test openfaas.

There is gateway deployment any function deployment.

Metrics are generated in gateway deployment.

Based on this metric I want to scale  function deployment.

Problem is that that HPA returns error:  "unable to get metric gateway_serv
ice_count: no metrics returned from custom metrics API"

If I ask for this metric manually it works:

```
 kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/openfaas/pods/*/gateway_service_count" | jq '.items[].value'
"2"
"2"
"2"
"2"
"2"
"2"
"2"
"2"
```

I think it generates error because in metics adatper it asks for this metric labeled with pod name

`http://prometheus-cs.default.svc:9090/api/v1/query?query=sum(gateway_service_count{namespace="openfaas",pod=~"hello-java8func-7644db6467-2q8w6|hello-java8func-7644db6467-9zhmd"}) by (pod)&time=1544615184.475
`

In prometheus gui I can see this metric is labeled with gateway pod

`gateway_service_count{app="gateway",function_name="hello-java8func",instance="10.32.0.19:8080",job="kubernetes-pods",namespace="openfaas",pod="gateway-55c5ddfcd8-x5n5p",pod_template_hash="55c5ddfcd8"}
`

My question is :
How can I avoid pod label in prometheus query to scale pod X based on pod Y ?

**Comment by john-delivuk** [comment]
Hey @marcin-kasinski I think external metrics are actually the answer to doing this. You'll be able to target those metrics from your desired pod(s). While work is ongoing, it would most likely be the simplest way to accomplish this.

**Comment by marcin-kasinski** [comment]
Hello John.
Thank you for your reply.
Can you give me additional information ?
k8s-prometheus-adapter implements only custom metrics not external metrics.

**Comment by john-delivuk** [comment]
Today correct, the work is in progress for external and it will hopefully be available soon. Once available I can help you with your config.

**Comment by alexellis** [comment]
This looks interesting. If you'd like to collaborate or ask questions on Slack let us know via https://docs.openfaas.com/community

Alex
