### ISSUE TITLE
gencert.sh mentioned in Example Deployment doesn't exist.

### ISSUE THREAD

**Issue by Rajat-0** [kubernetes-sigs/prometheus-adapter#163]

**Comment by anderson4u2** [comment]
it was delete here =S
https://github.com/coreos/prometheus-operator/commit/934b8930383c2bc94b8293d54ceb36eaf9e88e27#diff-5383fa9a91190a095548c7391d7ba65f

**Comment by anderson4u2** [comment]
it was still here: https://github.com/coreos/prometheus-operator/blob/34651838915ef8c83e374f9f7b9c5ffe6525eddf/contrib/kube-prometheus/experimental/custom-metrics-api/gencerts.sh

**Comment by Rajat-0** [comment]
@anderson4u2 Thanks for the help.

**Comment by anderson4u2** [comment]
you're welcome, although this change still needs to be addressed by the maintainer
