### ISSUE TITLE
Support cross-namespace metrics

### ISSUE THREAD

**Issue by agolomoodysaada** [kubernetes-sigs/prometheus-adapter#195]
I have an exporter exposing kafka metrics from namespace A.
I have an deployment and hpa in namespace B that need to scale based on metrics from namespace A.

Today it is not supported to pull metrics from a different namespace into the HPA.
Is there a workaround for this?
Can I enforce the adapter to write metrics into a specific namespace?
Can we implement this into the library itself?

Thank you

**Comment by AshMenhennett** [comment]
I have the same issue. I don't see a way around it without making some changes. In particular, this PR implemented the changes that have broken cross namespace metrics:  https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/197/files

**Comment by iAmMrinal0** [comment]
Did you get it working @agolomoodysaada? I have the same exact use case as you described and am not sure how to go about it.

**Comment by AshMenhennett** [comment]
@iAmMrinal0 have a look at this thread https://github.com/kubernetes-sigs/prometheus-adapter/pull/252#discussion_r369568355

The suggested way forward was to use Prometheus recording rules to ensure the metrics are also written with a label for the other namespace. I haven't validated this - keen to see how this looks.

**Comment by iAmMrinal0** [comment]
Thanks. I'll try this out if that's the suggested way and write something out if it all works out.
