### ISSUE TITLE
In makefile scripts, the cross-compilation of go language lacks GOOS = Linux

### ISSUE THREAD

**Issue by liguozhong** [kubernetes-sigs/prometheus-adapter#199]
In makefile scripts, the cross-compilation of go language lacks GOOS = Linux

Original ：
CGO_ENABLED=0 GOARCH=$*
After modification：
GOOS=linux
CGO_ENABLED=0 GOOS=$(GOOS) GOARCH=$*

**Comment by paulfantom** [comment]
Looks like a simple modification. Could you create a PR?
