### ISSUE TITLE
Prometheus Adapter often returns Unauthorized 

### ISSUE THREAD

**Issue by manojbadam** [kubernetes-sigs/prometheus-adapter#205]
Prometheus Adapter often enters a state where it only returns 403 Unauthorized.
```
$ kubectl logs prometheus-adapter-7fd4744b9-gzgkj -n monitoring -c prometheus-adapter
E0517 17:41:01.378514       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority]
E0517 17:41:01.987000       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority]
E0517 17:41:02.479795       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority]
E0517 17:41:02.566827       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority]
```
After delete all prometheus-adapter pods, it starts working fine. Running Prometheus-adapter with below arguments
```
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
        - --secure-port=6443
```

This is very intermittent issue, didn't see any pattern. Any suggestions/workarounds ?

Also. If I want to use custom tls [certs](https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/deploy/manifests/custom-metrics-apiserver-deployment.yaml#L25-L26) instead of self generated, what will be the subject and alternative names ?

**Comment by liguozhong** [comment]
2.Create a secret called `cm-adapter-serving-certs`

Example Deployment
==================

1. Make sure you've built the included Dockerfile with `make docker-build`. The image should be tagged as `directxman12/k8s-prometheus-adapter:latest`.

2. Create a secret called `cm-adapter-serving-certs` with two values:
   `serving.crt` and `serving.key`. These are the serving certificates used
   by the adapter for serving HTTPS traffic.  For more information on how to
   generate these certificates, see the [auth concepts
   documentation](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md)
   in the apiserver-builder repository.
   The kube-prometheus project published two scripts [gencerts.sh](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/experimental/custom-metrics-api/gencerts.sh)
   and [deploy.sh](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/experimental/custom-metrics-api/deploy.sh) to create the `cm-adapter-serving-certs` secret.

3. `kubectl create namespace custom-metrics` to ensure that the namespace that we're installing
   the custom metrics adapter in exists.

4. `kubectl create -f manifests/`, modifying the Deployment as necessary to
   point to your Prometheus server, and the ConfigMap to contain your desired
   metrics discovery configuration.

**Comment by woodliu** [comment]
@DirectXMan12 Could you help with this issue? I face the same problem when i enable "caBunle", without it, it can fetch the value
```
# kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/*/kube_pod_container_resource_requests -v 8
I1121 16:21:36.305976  123960 loader.go:359] Config loaded from file /root/.kube/config
I1121 16:21:36.306912  123960 round_trippers.go:383] GET https://prod-cluster.aliocp.csvw.com:8443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests
I1121 16:21:36.306940  123960 round_trippers.go:390] Request Headers:
I1121 16:21:36.306950  123960 round_trippers.go:393]     Accept: application/json, */*
I1121 16:21:36.306960  123960 round_trippers.go:393]     User-Agent: kubectl/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0
I1121 16:21:36.332709  123960 round_trippers.go:408] Response Status: 503 Service Unavailable in 25 milliseconds
I1121 16:21:36.332742  123960 round_trippers.go:411] Response Headers:
I1121 16:21:36.332757  123960 round_trippers.go:414]     Cache-Control: no-store
I1121 16:21:36.332771  123960 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1121 16:21:36.332785  123960 round_trippers.go:414]     Content-Length: 199
I1121 16:21:36.332794  123960 round_trippers.go:414]     Date: Thu, 21 Nov 2019 08:21:36 GMT
I1121 16:21:36.332826  123960 request.go:897] Response Body: Error: 'x509: certificate signed by unknown authority'
Trying to reach: 'https://10.84.139.234:443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests'
I1121 16:21:36.332915  123960 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server is currently unable to handle the request",
  "reason": "ServiceUnavailable",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "Error: 'x509: certificate signed by unknown authority'\nTrying to reach: 'https://10.84.139.234:443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests'"
      }
    ]
  },
  "code": 503
}]
F1121 16:21:36.333036  123960 helpers.go:119] Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**Comment by woodliu** [comment]
> @DirectXMan12 Could you help with this issue? I face the same problem when i enable "caBunle", without it, it can fetch the value
> 
> ```
> # kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/*/kube_pod_container_resource_requests -v 8
> I1121 16:21:36.305976  123960 loader.go:359] Config loaded from file /root/.kube/config
> I1121 16:21:36.306912  123960 round_trippers.go:383] GET https://prod-cluster.aliocp.csvw.com:8443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests
> I1121 16:21:36.306940  123960 round_trippers.go:390] Request Headers:
> I1121 16:21:36.306950  123960 round_trippers.go:393]     Accept: application/json, */*
> I1121 16:21:36.306960  123960 round_trippers.go:393]     User-Agent: kubectl/v1.11.0+d4cacc0 (linux/amd64) kubernetes/d4cacc0
> I1121 16:21:36.332709  123960 round_trippers.go:408] Response Status: 503 Service Unavailable in 25 milliseconds
> I1121 16:21:36.332742  123960 round_trippers.go:411] Response Headers:
> I1121 16:21:36.332757  123960 round_trippers.go:414]     Cache-Control: no-store
> I1121 16:21:36.332771  123960 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
> I1121 16:21:36.332785  123960 round_trippers.go:414]     Content-Length: 199
> I1121 16:21:36.332794  123960 round_trippers.go:414]     Date: Thu, 21 Nov 2019 08:21:36 GMT
> I1121 16:21:36.332826  123960 request.go:897] Response Body: Error: 'x509: certificate signed by unknown authority'
> Trying to reach: 'https://10.84.139.234:443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests'
> I1121 16:21:36.332915  123960 helpers.go:201] server response object: [{
>   "metadata": {},
>   "status": "Failure",
>   "message": "the server is currently unable to handle the request",
>   "reason": "ServiceUnavailable",
>   "details": {
>     "causes": [
>       {
>         "reason": "UnexpectedServerResponse",
>         "message": "Error: 'x509: certificate signed by unknown authority'\nTrying to reach: 'https://10.84.139.234:443/apis/custom.metrics.k8s.io/v1beta1/namespaces/mos-dts/pods/%2A/kube_pod_container_resource_requests'"
>       }
>     ]
>   },
>   "code": 503
> }]
> F1121 16:21:36.333036  123960 helpers.go:119] Error from server (ServiceUnavailable): the server is currently unable to handle the request
> ```
> 
> Openshift 3.11

I have slove the problem now，because openshift not trust the ca, you need to use the cluster ca to generate the certificates for adapter, then you can fetch metric with command "kubectl get --raw ..."

**Comment by calebwoofenden** [comment]
I am also seeing this error. I'm running the adapter inside a kube cluster managed by EKS. It's using the following args:
```
        - /adapter
        - --secure-port=6443
        - --cert-dir=/tmp/cert
        - --logtostderr=true
        - --prometheus-url=http://prometheus-ip-service.default.svc.cluster.local:9090
        - --metrics-relist-interval=1m
        - --v=2
        - --config=/etc/adapter/config.yaml
```
It doesn't seem to actually be interrupting service, it just spits out of a ton of these errors and fills up the logs. I'm able to query `custom.metrics.k8s.io` just fine and use it in my HPAs. Do I need to generate a certificate from the EKS CA for it?

**Comment by Hronom** [comment]
same trouble in EKS, can't fetch `http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/`
