### ISSUE TITLE
Troubleshooting missing metrics

### ISSUE THREAD

**Issue by sathibault** [kubernetes-sigs/prometheus-adapter#209]
I've followed the documentation, but not sure what the next step is.  HPA is unable to fetch metrics.  I've checked for the custom metrics:
```
$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
Error from server (NotFound): the server could not find the requested resource
```
Following the docs, I've added `--v=6` to the adapter.  From the `GET http://prometheus-k8s.monitoring.svc:9090/...` entries in the log, I've tested with curl and they return many metrics.

What can check next?

**Comment by s-urbaniak** [comment]
@sathibault Is prometheus adapter registered to serve the metrics API? What does `kubectl get apiservice` say?
