### ISSUE TITLE
Adapter logs SA token

### ISSUE THREAD

**Issue by omerlh** [kubernetes-sigs/prometheus-adapter#215]
While investigating other issues, I noticed the following log message:
```
I0624 08:01:48.067723       1 round_trippers.go:386] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: adapter/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer <>" 'https://10.0.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews'
```
I couldn't figure where this line of code coming from or what is writing this log, but this for sure does not need to be information. By looking at the code of the round tripper, look like this log is written only when using the `debuggingRoundTripper` (see this [method](https://github.com/kubernetes/client-go/blob/585a16d2e773e203c04e1ef624a56113d4c74705/transport/round_trippers.go#L412)). But I couldn't figure out where is the usage of this client.

Adapter version: `directxman12/k8s-prometheus-adapter-amd64:v0.5.01`.

**Comment by s-urbaniak** [comment]
I think this is deeper api machinery code, which invokes a subject access review to check if you have permissions to invoke the metrics API.
