### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by pdbogen** [kubernetes-sigs/prometheus-adapter#221]
howdy!

I'm seeing k8s-prometheus-adapter looking to use a pretty large amount of memory (~3GiB) on objectively small clusters, and I'm trying to understand if this is expected.

Can you advise on how to understand k8s-prometheus-adapter's memory footprint (what causes high memory use / many allocations?), and how to determine appropriate limits for it?

thanks,
- patrick

**Comment by pdbogen** [comment]
as an aside, it doesn't seem like k8s-prometheus-adapter exposes any metrics of its own? I found one registered metric in https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/pkg/client/metrics/metrics.go, but I couldn't see any evidence that it's presented for scraping anywhere.

**Comment by pdbogen** [comment]
(oops, I see #218 is about metrics as well. I'll follow that issue for the metrics side of things.)

**Comment by s-urbaniak** [comment]
@pdbogen are you running prometheus adapter with custom metrics enabled? If so, try to reduce the amount of discovered metrics and memory consumption should go down. It is an issue we are aware of and want to address this long term.

**Comment by anshupande** [comment]
if anyone here has any experience of filtering k8s-prometheus-adapter metrics.
```kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"```
has a lot of metics in the adapter that is not required.
Is there a way to blacklist based on say namespaces example if we can blacklist kube-system NS metrics or filtering based on some other criterion?
