### ISSUE TITLE
Deployment discovered as extensions/v1beta1 rather than apps/v1

### ISSUE THREAD

**Issue by tcolgate** [kubernetes-sigs/prometheus-adapter#224]
After a recent cluster upgrade some of our HPAs started failing with:
``` unable to map kind deployment to resource: no matches for kind "deployment" in group ""
```
The target in the metrics was set to "deployment", but no apiVersion was specified. I tried setting it to apps/v1, which I think is currently the correct api/version for a deployment resource. After querying the api, it shows the metrics are being created assuming extensions/v1beta1 (they appear ass deployments.extensions).

Is the current behaviour expected? Deploymens are a bit of a pain as they have moved API groups.

**Comment by s-urbaniak** [comment]
@tcolgate the error message seems to be missing. Can you add it?
