### ISSUE TITLE
Purpose of seriesQuery and relist interval?

### ISSUE THREAD

**Issue by weibeld** [kubernetes-sigs/prometheus-adapter#228]
In general, I had trouble understanding the purpose of the [Discovery](https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config.md#discovery) part of the metric rules configuration.

As far as I understood, the Prometheus Adapter makes an [`/api/v1/series`](https://prometheus.io/docs/prometheus/latest/querying/api/) request to Prometheus with the value of the `seriesQuery` field every *n* seconds, where *n* is the relist interval.

The response to this request is a list of label matchers for each time series matching the request.

But if a user makes a request to the Custom Metrics API, the Prometheus Adapter executes the PromQL query defined in `metricsQuery` (with a [`/api/v1/query`](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) request) anyway.

So, what's the purpose of periodically fetching the `/api/v1/series` data? Wouldn't the `metricsQuery` be enough, because that's what's executed when a user makes a request to the Custom Metrics API?

PS:

I'm using v0.5.0 and I couldn't observe metrics appearing and disappearing when the relist interval is smaller than the Prometheus scraping interval (e.g. scraping interval 10s and relist interval 2s). The metrics are just always there when I request them through the Custom Metrics API.

**Comment by tommyjcarpenter** [comment]
I have the same question here
