### ISSUE TITLE
how to Install multiple adapters pointing different prometheus servers

### ISSUE THREAD

**Issue by prageethw** [kubernetes-sigs/prometheus-adapter#267]
I'm trying to have multiple adapters pointing to different Prometheus servers in K8s cluster, for example, one istio default and one I use to monitor everything else.
Does this support at all?

**Comment by luks** [comment]
We had similar problem we solve it using Thanos (Thanos querier) which is capable to serve metric from n prometheus replicas

**Comment by geekyfox90** [comment]
That would be helpful

**Comment by s-urbaniak** [comment]
@prageethw the only way to have multiple prometheus-adapter installations natively today to point to different prometheus instances is to have separate deployments per API-type, that is a separate prometheus-adapter for resource, custom, and external metrics.

But there is a solution for your problem, that is Thanos Querier: you could deploy that component in front of your Prometheus servers and point prometheus-adapter to thanos-querier instead of the dedicated Prometheus.

**Comment by bwplotka** [comment]
Thanos Querier -> https://thanos.io/components/query.md/

**Comment by metalmatze** [comment]
There was even a KubeCon talk in Barcelona in May last year! :)

![Screenshot from 2020-02-13 11-01-15](https://user-images.githubusercontent.com/872251/74423251-3d3d5000-4e50-11ea-9c36-1ca726179f35.png)

https://www.youtube.com/watch?v=qTxunwzYO0g&t=1517s

**Comment by smitthakkar96** [comment]
to achieve this you need to use partial response strategy for which you need to specify partial_response in the query args which I guess is not possible to do with prometheus-adapter. https://github.com/thanos-io/thanos/blob/master/docs/components/query.md#partial-response 

There is no clear way to tell querier that for this metric look at this prometheus.

**Comment by s-urbaniak** [comment]
@smitthakkar96 for partial response, you can specify the `query.partial-response` flag as a startup parameter. also cc'ing @bwplotka (maintainer and founder of Thanos) and @metalmatze who both are part of the team I am working with here at RedHat if they have additional pointers or advise for your use case. As far as I see querier does not support metric based routing to different Prometheus instances, but if it is configured with partial response, it indeed will simply return the right data, unless i am missing something.

Don't get me wrong, I am not opposed, just careful to add additional complexity here if we have easy workarounds.
