### ISSUE TITLE
Is there an implementation for external.metrics.k8s.io API using Prometheus without using helm?

### ISSUE THREAD

**Issue by lianghao208** [kubernetes-sigs/prometheus-adapter#273]
I know there is an easy way to create a HPA with the external APIs from Prometheus by using helm.
But I am in a restricted network environment, which isnt allow me to build a helm repo, so I can only use a certain yaml file to create my pods, is there an example yaml file for me to approach external APIs?
ps: I use luxas' example yaml to create custom-metrics-api pods. I guess there must be an example yaml to create external-metrics-api pods as well.

**Comment by GMartinez-Sisti** [comment]
You can use helm to create the yaml files you need, and then apply those with kubectl.

Is this helpful? -> https://blog.giantswarm.io/what-you-yaml-is-what-you-get/
