### ISSUE TITLE
Multiple deployments of the prometheus adapter allowed?

### ISSUE THREAD

**Issue by diclophis** [kubernetes-sigs/prometheus-adapter#285]
Hello,

This is more of a question than an issue per se... Our team was wondering if its recommended to have a single "global" prometheus-adapter deployment (with all of our apps metrics registered in it), or if it is possible to have a deployment per application/namespace?

**Comment by jurgenweber** [comment]
to further on this, what is considered the preferred HA setup. Is it limited like the metrics server and you only have vertical scaling options or something else?

**Comment by ChristopherLenz** [comment]
I'd like to join this "issue" with a more concrete question. We have a **shared cluster** with **multiple teams** working on it. If 2 teams decide to use this adapter we will get problems if the APIService.Group is the same? Are there any other things to take in mind?

**Comment by diclophis** [comment]
@ChristopherLenz our teams use-case is very similar to yours ... I would be interested in hearing about any solutions you came up with!

**Comment by ChristopherLenz** [comment]
> @ChristopherLenz our teams use-case is very similar to yours ... I would be interested in hearing about any solutions you came up with!

I'm afraid not. We asked the team which hosts the kubernetes to provide this as a cluster-wide service. No real solution for the problem/need itself.

**Comment by diclophis** [comment]
@ChristopherLenz thanks for the reply, yea its a bit of a bummer ... though after digging in I can see why it would be problematic to support multiple registrations of the custom apiserver endpoint ...
