### ISSUE TITLE
node cpu stats don't work with kind

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes-sigs/prometheus-adapter#288]
cannot query `kubectl top nodes` due to cpu query does not return result

* deployed k8s-prometheus-adapter using helm
* [memory query works](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-adapter-configMap.yaml#L20)
* [cpu query does not work](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-adapter-configMap.yaml#L8)
* kind version: v0.7.0
* k8s version: v1.18.0

I tried these queries, but I am not a promql expert...

"nodeQuery": "sum(1 - irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m]) * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{<<.LabelMatchers>>}) by (<<.GroupBy>>)"

"nodeQuery": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m])) * 100)"

**Comment by janavenkat** [comment]
Any update?
Am running k8s version: v1.14
