### ISSUE TITLE
pod_name had been removed in k8s 1.16

### ISSUE THREAD

**Issue by scott2449** [kubernetes-sigs/prometheus-adapter#289]
The default seriesQuery in the adapter :

`{__name__=~"^container_.*",container_name!="POD",namespace!="",pod_name!=""}`

This query returns no data in Kubernetes 1.16 and later because pod_name was removed:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md

**Comment by kuberkaul** [comment]
+1

**Comment by dgrisonnet** [comment]
Now that https://github.com/kubernetes-sigs/prometheus-adapter/pull/386 was merged, we can close this issue.

/close
