### ISSUE TITLE
Could not get the default configuration (also custom query) to work

### ISSUE THREAD

**Issue by arvin6msd** [kubernetes-sigs/prometheus-adapter#301]
How am I installing adapter?
`helm install --name prom-adapter stable/prometheus-adapter --namespace monitoring --set prometheus.url="http://promop-v1-prometheus-o-prometheus.monitoring.svc",prometheus.port="9090" --set image.tag="v0.6.0" --set rbac.create="true"`

Error:
`I0714 14:15:22.771812       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (280.151µs) 200 [kubectl/v1.16.0 (linux/amd64) kubernetes/2bd9643 192.168.8.87:57998]
I0714 14:15:23.306719       1 wrap.go:47] GET /apis/custom.metrics.k8s.io/v1beta1?timeout=32s: (1.562352ms) 200 [aws-k8s-agent/v0.0.0 (linux/amd64) kubernetes/$Format 192.168.94.246:45320]
E0714 14:15:24.922172       1 provider.go:209] unable to update list of all metrics: unable to fetch metrics for query "{namespace!=\"\",__name__!~\"^container_.*\"}": bad_response: unknown response code 404`

The config that errors out:
`apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: '{__name__=~"^container_.*",container!="POD",namespace!="",pod!=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^container_(.*)_seconds_total$
        as: ""
      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[5m]))
        by (<<.GroupBy>>)`

**Comment by arvin6msd** [comment]
I'm trying to set up hpa based on request rates and couldn't get the adapter to work properly even with the default setup.

**Comment by rishi1111** [comment]
Any Luck with this, im also trying to install prometheus adapter with helm charts.
