### ISSUE TITLE
Multiple services scaling using custom metrics

### ISSUE THREAD

**Issue by kmokashi** [kubernetes-sigs/prometheus-adapter#305]
Hello,

I have a question. Can we scale 2 services by using custom metrics. For example, I have 2 services which needs auto scaling based on custom metrics:

- First service needs to be scaled based on number of messages in Kafka queue.

- Second service needs to be scaled based on http requests per second.

I am able to scale first service by using custom metrics  with prometheus and prometheus adapter. Now in order to scale second service what needs to be done? All articles available online are for scaling single service only. Is it possible to scale multiple services using custom metrics? If yes then how can we achieve it?
Thanks in advance.

**Comment by Ping-Lin-108** [comment]
not sure if these 2 services has anything related to each other. but if you need to scale another service, I think just create another hpa and target to the service metric.

**Comment by dobesv** [comment]
If you have a metric for the number of messages in a kafka queue it is technically possible to scale based on this, but documentation is not great, you'll have to dig around to figure out the right YAML configs for this custom metrics process and in the HPA config.
