### ISSUE TITLE
Canonical repo address is inconsistent with go import path

### ISSUE THREAD

**Issue by KateGo520** [kubernetes-sigs/prometheus-adapter#306]
The github.com/`directxman12/k8s-prometheus-adapter` repo was just renamed to github.com/`DirectXMan12/k8s-prometheus-adapter`
This means that the canonical github repo address now conflicts with canonical go import packages (for example, `"github.com/directxman12/k8s-prometheus-adapter/pkg/client"`, as referenced from https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/v0.7.0/pkg/client/fake/client.go#L23)

It is now very easy for downstream consumers (which don't import "github.com/directxman12/k8s-prometheus-adapter/..." packages) to accidentally clone and add imports to upper-case `"github.com/DirectXMan12/k8s-prometheus-adapter/..."` packages. This will create many pitfalls and break the module users. They may encounter errors:
```
go get: github.com/DirectXMan12/k8s-prometheus-adapter@v0.7.0: parsing go.mod:
        module declares its path as: github.com/directxman12/k8s-prometheus-adapter
                but was required as: github.com/DirectXMan12/k8s-prometheus-adapter
```

(This was possible before, but way harder to do accidentally, since all the links and clone commands from github agreed with the canonical go import packages)

Cautionary tale:
* [sirupsen/logrus#570 (comment)](https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276)

Please consider reverting the `directxman12` -> `DirectXMan12` rename.

If the case change is here to stay, some things that would help a lot:

1) Example `go get github.com/directxman12/k8s-prometheus-adapter` commands or others in the READMEs of all the go repos to guide consumers. 
2) Add canonical import paths with the correct case (https://golang.org/doc/go1.4#canonicalimports) to prevent accidental use of the wrong case downstream.

**Comment by KateGo520** [comment]
@smarterclayton @sergii-koshel-exa  Could you help me review this issue? Thx :p

**Comment by s-urbaniak** [comment]
We are planning to move this repository into a more kubernetes canonical organization. Once this happens the issue should resolve itself.
