### ISSUE TITLE
Allow passing bare Prometheus query; drop metric discovery

### ISSUE THREAD

**Issue by brancz** [kubernetes-sigs/prometheus-adapter#31]
From what I can tell, the "metric discovery" currently being performed only exists to allow doing `rate` functions with a single metric "name". One can always create recording rules, but that would mean, that one also has access to modify the Kubernetes config.

At the point where one is using this adapter that person/organization has already sold into the Prometheus ecosystem pretty heavily: dashboards, alerts, etc.

Furthermore currently a very specific set of labels are expected in order for a metric to be associated with an object. This is not necessarily the case. For example a distributed worker infrastructure should be horizontally scaled based on the queue length of a certain queue of the message broker cluster, meaning currently this requires hacks as the metric for that queue would not have the respective labels. This is the most common use of custom metrics, in fact I've already been approached multiple times regarding this issue.

I propose to drop the resource intensive metric discovery and allow passing bare Prometheus queries. Even metric names are likely specific to Prometheus naming conventions, so I don't think it makes a lot of sense to try and generalize where the generalization doesn't even give us a benefit.

@DirectXMan12

**Comment by DirectXMan12** [comment]
> From what I can tell, the "metric discovery" currently being performed only exists to allow doing rate functions with a single metric "name".

Metric discovery also allows us to serve a Kubernetes discovery document, which lets us behave more like a traditional Kubernetes API.  If we ever want to support sharding by topic, it'll also allow us to easily do that.

> For example a distributed worker infrastructure should be horizontally scaled based on the queue length of a certain queue of the message broker cluster, meaning currently this requires hacks as the metric for that queue would not have the respective labels.

If it is coming from a Kubernetes cluster, and "object" metric should work.  If not, I'd suggest a recording rule, although I feel your pain.

> I propose to drop the resource intensive metric discovery and allow passing bare Prometheus queries. Even metric names are likely specific to Prometheus naming conventions, so I don't think it makes a lot of sense to try and generalize where the generalization doesn't even give us a benefit.

This has a number of issues.  First, it's *really* hard to properly secure this without doing some sort of query parsing.  Second, as mentioned above, we'd lose API discoverability, which is useful for a number of things (it's easier to give better error messages about metric not existing vs other conditions, among other things).  Third, it makes it a lot easier for users to run maliciously complicated queries against your cluster.

I'd much rather find a solution that lets us reference metrics that aren't labeled according to the Kubernetes instrumentation conventions than drop discovery.

**Comment by brancz** [comment]
Your arguments make sense, specifically the security once I did not think about. I can't get over the fact that one needs to modify Prometheus recording rules to specify an autoscaling query/metrics, as let's be honest most of the time it's not a single metric. This feels more than quirky. Not happy yet with the situation, but I'll keep thinking about it. Thanks for sharing your thoughts!

> I'd much rather find a solution that lets us reference metrics that aren't labeled according to the Kubernetes instrumentation conventions than drop discovery.

This is definitely also something I'd like to discuss.

**Comment by DirectXMan12** [comment]
> I can't get over the fact that one needs to modify Prometheus recording rules to specify an autoscaling query/metrics, as let's be honest most of the time it's not a single metric

I agree to a certain extent (although I also think adding recording rules in a distributed manner shouldn't necessarily be as big of a hassle as it is...)

**Comment by tcolgate** [comment]
I've really only just got things up and running, but the metrics discovery does worry me a little in terms of scalablility and load. It seems like it would be better to only discover metrics that have been requested by HPAs (does anything else use them?), and provide suitable errors the resulting lookups don't return errors.
  I have prom servers with > 600k active time series and querying all of that for the sake of a few custom metrics seems very wasteful. Some black/white listing might improve things, but the ratio of "desirable" metrics for use by a HPA, vs available metrics for monitoring, seems so high that blanket scraping of overything seems like it is never going to be the better option.

**Comment by brancz** [comment]
I absolutely agree, this is certainly a scalability issue. My feeling is that a whitelist should definitely work, as you as a cluster administrator would configure the "metrics" available and skip the discovery part all together. More dynamic whitelist/blacklist approaches seem more difficult as the Prometheus endpoints don't allow filtering as far as I remember.
