### ISSUE TITLE
How to replace metrics server to complete the function of kubectl top

### ISSUE THREAD

**Issue by Cweiping** [kubernetes-sigs/prometheus-adapter#310]
I can see that the adapter is docking `custom.metrics.k8s.io` API supports HPA custom metrics, but it does not completely replace the functions of metrics-server. `kubectl top` doesn't work when I create `apiservice/v1beta1.metrics.k8s.io`.

How should I implement this scenario?

**Comment by s-urbaniak** [comment]
If you configure `resourceRules` section the prometheus-adapter will also host resource metrics, see the deployment example in https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/7a421bb91e9ea52be4e26db22392c36c8af38bc8/deploy/manifests/custom-metrics-config-map.yaml#L73-L98.
