### ISSUE TITLE
Feature Proposal: Support # in metric labels

### ISSUE THREAD

**Issue by carsonoid** [kubernetes-sigs/prometheus-adapter#323]
We have [nsq](https://nsq.io/) metrics in Prometheus. We are able to export these using the adapter.

## Problem

In some cases we are unable to use the adapter to filter metrics based on topic or channel because our topics and channels can contain `#`, which is a valid Prometheus label value but not a valid Kubernetes label value.

## Proposed Solution

I propose that we add the ability to enable special Prometheus <-> Kubernetes label replacements strings for label values.

Allow a special string (`_HaSh_`) to be put into metric queries coming into the api. This string is Kubernetes label-safe and it  will be replaced by the adapter before sending the query to Prometheus.

So for example, a query trying to match the K8s labels of `topic=my_HaSh_topic,channel=my_HaSh_chan` would actually send a Prometheus query with the labels: `topic="my#topic", channel="my#channel"`. The only drawback being that metrics would be unable to include a literal `_HaSh_` but that seems unlikely.

Right now I have only done this with `#` but there may be other Prometheus labels that are not Kubernetes-safe that could be replaced in the same way.

We could put this behind a flag if we want to make it an opt-in feature but it would enable the adapter to support the full range of prometheus label values while not breaking Kubernetes API promises.

I am already running a fork of the adapter in production with this feature and would be happy to upstream the code if the proposal is accepted.

**Comment by paulfantom** [comment]
Weird, it looks like there is something undocumented on prometheus side as according to https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels `#` is not a valid character in label name. Quote:

> Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.

**Comment by carsonoid** [comment]
/remove-lifecycle stale

I'll go ahead and create a PR with the proposed change.
