### ISSUE TITLE
Suggested deployment configuration does not set resource limits / requests

### ISSUE THREAD

**Issue by dobesv** [kubernetes-sigs/prometheus-adapter#332]
It would probably be nice to have some idea how much memory & CPU this needs so it can be scheduled to a node with enough resources and not get OOMKilled.

I noticed while running it, it actually uses a fair amount of memory, which surprised me.

![image](https://user-images.githubusercontent.com/327833/97956967-ce49b380-1d5e-11eb-84ee-fb337ad0213e.png)

**Comment by s-urbaniak** [comment]
@dobesv It really depends how you use k8s-prometheus-adapter. Do you mind sharing your configuration?

Unfortunately prometheus-adapter is not very well optimized with respect to custom and external metrics, especially regarding memory usage. It grows the bigger or more complex your configuration is.

**Comment by dobesv** [comment]
A recent version of my config is here:

https://gist.github.com/dobesv/24a5f81bddd1a7008135f3763abec4d5

I've since added more replicas and pod anti affinity to it, but the actual configuration parts have not changed.

I guess it's tough to decide whether to put some kind of "default" resources in the example configs or leave it absent.  I think it's nice to have that in there so that people will see it and think to modify it if necessary.
