### ISSUE TITLE
Set host problem

### ISSUE THREAD

**Issue by carpino** [kubernetes-sigs/prometheus-adapter#337]
Hi i have tried deploing the adapter in two different ways but I have obtained errors for both, this is what I have done:

helm install adapter --namespace default --set prometheus.url=prometheus-server.default.svc.cluster.local --set prometheus.port=80 prometheus-community/prometheus-adapter

—>

E1116 16:32:35.161193       1 provider.go:209] unable to update list of all metrics: unable to fetch metrics for query "{__name__=~\"^container_.*\",container!=\"POD\",namespace!=\"\",pod!=\"\"}": Get prometheus-server.default.svc.cluster.local:80?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod%21%3D%22%22%7D&start=1605543155.161: unsupported protocol scheme "prometheus-server.default.svc.cluster.local"

helm install adapter --namespace default prometheus-community/prometheus-adapter

—> 

E1116 16:34:38.950087       1 provider.go:209] unable to update list of all metrics: unable to fetch metrics for query "{__name__=~\"^container_.*\",container!=\"POD\",namespace!=\"\",pod!=\"\"}": Get http://prometheus.default.svc:9090/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod%21%3D%22%22%7D&start=1605543278.937: dial tcp: lookup prometheus.default.svc on 172.20.0.10:53: no such host

prometheus-server.default.svc.cluster.local with port 80 is what I get if I execute helm status prometheus as a way to access it, what could be the problem? Thanks

**Comment by dgrisonnet** [comment]
Hi @carpino, you need to add the protocol scheme when specifying the url of your prometheus server. In your case:
```
prometheus.url=http://prometheus-server.default.svc.cluster.local
```
