### ISSUE TITLE
kubectl panic 

### ISSUE THREAD

**Issue by cctv86** [kubernetes-sigs/prometheus-adapter#338]
Hi, I just found a issue, please help me.

kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/prometheus_http_requests"	

/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc00090acc0, 0x20b7540, 0xc000fd5a40, 0xc038520b00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:91 +0x2a4
net/http.HandlerFunc.ServeHTTP(0xc00090ace0, 0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc00090ad00, 0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000749f20, 0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0007dcee0, 0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.initNPNRequest.ServeHTTP(0x20c3100, 0xc004afd1d0, 0xc004d4d880, 0xc0007dcee0, 0x20aac40, 0xc006afd000, 0xc0382c5c00)
	/usr/local/go/src/net/http/server.go:3395 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc000b9d800, 0xc006afd000, 0xc0382c5c00, 0xc0384da680)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2147 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1881 +0x4e5
E1118 08:36:10.964071       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 8006 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0386e0900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1aa1b60, 0x3189600)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc035c10fd0, 0xc03851a300, 0x71, 0x71, 0x30, 0x1b79a80, 0xc036cb4c01)
	/usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0036de5f0, 0xc03851a300, 0x71, 0x71, 0xc03851a300, 0x71, 0x71)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1d35b02, 0x10, 0x7fe500eb50c0, 0xc0037e5b80, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00, 0xc8, 0x2096640, 0xc0036de5a0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x20b9640, 0xc00068d7a0, 0x20b98c0, 0x31ce040, 0x0, 0x0, 0x0, 0x0, 0x7fe500eb5030, 0xc038504230, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc0005d4480, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:81 +0x17b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:77
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000736360, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:294 +0x635
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:204
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1d44a83, 0x1a, 0xc000736360, 0xc0001242a0, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x531
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x548
net/http.HandlerFunc.ServeHTTP(0xc00069d740, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4f6
net/http.HandlerFunc.ServeHTTP(0xc000749e90, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x22f3
net/http.HandlerFunc.ServeHTTP(0xc00069d780, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ea
net/http.HandlerFunc.ServeHTTP(0xc00063cff0, 0x7fe500eb5030, 0xc038504230, 0xc0381cfc00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0386e0900, 0xc00090ac80, 0x20c3800, 0xc038504230, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb

goroutine 7974 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19fddc0, 0xc038a4ce50)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc02b963c90, 0x1, 0x1)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x19fddc0, 0xc038a4ce50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00090ac80, 0x20b7540, 0xc000b70e00, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x20b7540, 0xc000b70e00, 0xc0381cfb00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc000749ec0, 0x20b7540, 0xc000b70e00, 0xc0381cfb00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x20b7540, 0xc000b70e00, 0xc0381cfa00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc000749ef0, 0x20b7540, 0xc000b70e00, 0xc0381cfa00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1(0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc00090aca0, 0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc00090acc0, 0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:91 +0x2a4
net/http.HandlerFunc.ServeHTTP(0xc00090ace0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc00090ad00, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000749f20, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0007dcee0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.initNPNRequest.ServeHTTP(0x20c3100, 0xc004afd1d0, 0xc004d4d880, 0xc0007dcee0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:3395 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc000b9d800, 0xc006afcfe8, 0xc0382c5600, 0xc0384da620)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2147 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1881 +0x4e5
E1118 08:36:10.964107       1 wrap.go:39] apiserver panic'd on GET /apis/custom.metrics.k8s.io/v1beta1
http2: panic serving 10.10.128.28:55974: runtime error: invalid memory address or nil pointer dereference
goroutine 8006 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0386e0900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1aa1b60, 0x3189600)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
compress/gzip.(*Writer).Write(0xc035c10fd0, 0xc03851a300, 0x71, 0x71, 0x30, 0x1b79a80, 0xc036cb4c01)
	/usr/local/go/src/compress/gzip/gzip.go:168 +0x237
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc0036de5f0, 0xc03851a300, 0x71, 0x71, 0xc03851a300, 0x71, 0x71)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:182 +0x54e
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x1d35b02, 0x10, 0x7fe500eb50c0, 0xc0037e5b80, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00, 0xc8, 0x2096640, 0xc0036de5a0)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:117 +0x389
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x20b9640, 0xc00068d7a0, 0x20b98c0, 0x31ce040, 0x0, 0x0, 0x0, 0x0, 0x7fe500eb5030, 0xc038504230, ...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).ServeHTTP(0xc0005d4480, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:81 +0x17b
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery.(*APIVersionHandler).handle(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/discovery/version.go:77
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000736360, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:294 +0x635
github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful/container.go:204
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x1d44a83, 0x1a, 0xc000736360, 0xc0001242a0, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x531
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x548
net/http.HandlerFunc.ServeHTTP(0xc00069d740, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:175 +0x4f6
net/http.HandlerFunc.ServeHTTP(0xc000749e90, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x22f3
net/http.HandlerFunc.ServeHTTP(0xc00069d780, 0x7fe500eb5030, 0xc038504230, 0xc0381cfd00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fe500eb5030, 0xc038504230, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ea
net/http.HandlerFunc.ServeHTTP(0xc00063cff0, 0x7fe500eb5030, 0xc038504230, 0xc0381cfc00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0386e0900, 0xc00090ac80, 0x20c3800, 0xc038504230, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
created by github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb

goroutine 7974 [running]:
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc006afcfe8, 0xc02b963f67, 0xc000b9d800)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2140 +0x16b
panic(0x19fddc0, 0xc038a4ce50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc02b963c90, 0x1, 0x1)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x19fddc0, 0xc038a4ce50)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00090ac80, 0x20b7540, 0xc000b70e00, 0xc0381cfc00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x20b7540, 0xc000b70e00, 0xc0381cfb00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc000749ec0, 0x20b7540, 0xc000b70e00, 0xc0381cfb00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x20b7540, 0xc000b70e00, 0xc0381cfa00)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc000749ef0, 0x20b7540, 0xc000b70e00, 0xc0381cfa00)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1(0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0x1a0
net/http.HandlerFunc.ServeHTTP(0xc00090aca0, 0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc00090acc0, 0x20b7540, 0xc000b70e00, 0xc0381cf900)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:91 +0x2a4
net/http.HandlerFunc.ServeHTTP(0xc00090ace0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc00090ad00, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2036 +0x44
github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000749f20, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0007dcee0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.initNPNRequest.ServeHTTP(0x20c3100, 0xc004afd1d0, 0xc004d4d880, 0xc0007dcee0, 0x20aac40, 0xc006afcfe8, 0xc0382c5600)
	/usr/local/go/src/net/http/server.go:3395 +0x8d
github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc000b9d800, 0xc006afcfe8, 0xc0382c5600, 0xc0384da620)
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:2147 +0x9f
created by github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/directxman12/k8s-prometheus-adapter/vendor/golang.org/x/net/http2/server.go:1881 +0x4e5

**Comment by dgrisonnet** [comment]
Hi, it seems that you are querying an invalid endpoint. You should use the following command instead:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/metrics/prometheus_http_requests"
```

If you want to know the different API paths of the custom metrics API, you can find them here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/custom-metrics-api.md#api-paths

**Comment by cctv86** [comment]
@dgrisonnet thanks for your help
