### ISSUE TITLE
Hpa is failing with the following specification.

### ISSUE THREAD

**Issue by munipravy** [kubernetes-sigs/prometheus-adapter#340]
@DirectXMan12 dgrisonnet 
Deployed Prometheus adaptor in kubernetes version 1.17

followed steps from below git repo for deploying prometheus adaptor 
https://github.com/DirectXMan12/k8s-prometheus-adapter/tree/df3d247308816266b471032d2c6e9ff74d95fe06/deploy/manifests

Adaptor deplyment yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: custom-metrics
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      affinity: {}
      containers:
      - args:
        - /adapter
        - --secure-port=6443
        - --cert-dir=/tmp/cert
        - --logtostderr=true
        - --prometheus-url=http://prometheus-service-ui.namespace.svc.cluster.local:80
        - --metrics-relist-interval=1m
        - --v=4
        - --config=/etc/adapter/config.yaml
        image: directxman12/k8s-prometheus-adapter-amd64:v0.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: custom-metrics-apiserver
        ports:
        - containerPort: 6443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/adapter/
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: custom-metrics-apiserver
      serviceAccountName: custom-metrics-apiserver
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: adapter-config
        name: config
      - emptyDir: {}
        name: tmp

Create kafka consumer application 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-consumer-application
  labels:
    app_name:  kafka-consumer-application
spec:
  revisionHistoryLimit: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0      
      maxSurge: 10
  replicas: 1
  selector:
    matchLabels:
      app_name:  kafka-consumer-application
  template:
    metadata:
      labels:
        app_name:  kafka-consumer-application
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9308'
    spec:
      containers:
        - name:  kafka-application
          image:  confluentinc/cp-kafka:5.0.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              while true
                do
                kafka-console-consumer --bootstrap-server prom-kafka-kafka-bootstrap.namespace.svc.cluster.local:9092 --topic test --from-beginning --group testgroup --timeout-ms 2000
                sleep 1
              done
              
 Hpa Definations
 
 kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: kafka-hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer-application
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: "kafka_consumergroup_lag"
      targetAverageValue: 100

**Comment by dgrisonnet** [comment]
@munipravy did you add the `kafka_consumergroup_lag` metric to the prometheus-adapter configmap or just deployed the manifests as they are in this project?

Also, can you please give me the output of the following query?
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/pods/*/kafka_consumergroup_lag"
```
