### ISSUE TITLE
document links are broken

### ISSUE THREAD

**Issue by victor23d** [kubernetes-sigs/prometheus-adapter#349]
https://github.com/DirectXMan12/k8s-prometheus-adapter/tree/master/deploy
> "The kube-prometheus project published two scripts gencerts.sh and deploy.sh to create the cm-adapter-serving-certs secret."

When I click the gencerts.sh and deploy.sh, the links are broken. Please update them.

**Comment by victor23d** [comment]
Maybe this link: 
https://github.com/prometheus-operator/kube-prometheus/blob/62fff622e9900fade8aecbd02bc9c557b736ef85/experimental/custom-metrics-api/gencerts.sh
https://github.com/prometheus-operator/kube-prometheus/blob/62fff622e9900fade8aecbd02bc9c557b736ef85/experimental/custom-metrics-api/deploy.sh

**Comment by dgrisonnet** [comment]
Yes these links seems to be the correct ones, although I'm not sure why these scripts were removed in the first place. @s-urbaniak   do you have any idea?

**Comment by s-urbaniak** [comment]
hmm, i do not recall, this potentially predates when i took over the project :thinking:

**Comment by andrewpollack** [comment]
PR Merged. Issue can be closed
