### ISSUE TITLE
Please let me know how to install if Prometheus is already installed in different namspace.

### ISSUE THREAD

**Issue by Chetan496** [kubernetes-sigs/prometheus-adapter#350]
**Question**
This is a question regarding the usage.
I have Prometheus already setup in a namespace called 'prometheus'
The pods (which I want the metrics for ) are running in a different namespace called 'development'
How do I setup the prometheus adapter using Helm? And which namespace should I use?
Sorry, I am new to Helm and Kubernetes , so need help.

**Version of Helm and Kubernetes**:

Helm Version: 3.2.4

```console
$ helm version
please put the output of it here
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dgrisonnet** [comment]
Hello @Chetan496,

I'd suggest you to run prometheus-adapter in the same namespace as prometheus, but this is a not a requirement, you can put them in separate namespaces.

> How do I setup the prometheus adapter using Helm?

If you really want to use Helm to deploy the prometheus-adapter, it might be best to ask this question to the maintainers of the chart on their repository. None of the maintainers of this project are using Helm so they won't be able to help you with it.

That being said, this project provide a walkthrough https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md that might help you better understand the project itself and how to autoscale your applications.

**Comment by Chetan496** [comment]
@dgrisonnet thanks for the response.
yes, I went through the walkthrough and I understand few things now.

I see that I will have to install the prometheus-operator first, and my application also has to expose the metrics on /metrics.
Then I can carry on next steps.

Thanks again, I see I need to have few things setup , then I can use prometheus-adpater
