### ISSUE TITLE
Image doesn't exist? 

### ISSUE THREAD

**Issue by kerneljack** [kubernetes-sigs/prometheus-adapter#36]
Hi I'm trying to follow the walkthrough and deploy the custom metrics adapter but it seems that the image doesn't exist anymore?

```
Warning  Failed                 15s                kubelet, gke-custom-metrics-default-pool-293ce8a3-1tj5  Failed to pull image "directxman12/k8s-prometheus-adapter": rpc error: code = Unknown desc = Error response from daemon: manifest for directxman12/k8s-prometheus-adapter:latest not found
```

**Comment by DirectXMan12** [comment]
I don't actually have a `:latest` image tagged at the moment.  Right now, I'd recommend building an image yourself.  Otherwise, I'll try to have an image set up soon.

**Comment by soorajchirag** [comment]
From docker.io, I see the following images:

> [root@scspa0413804001 ~]# sudo docker pull -a directxman12/k8s-prometheus-adapter
> Trying to pull repository registry.access.redhat.com/directxman12/k8s-prometheus-adapter ...
> Trying to pull repository docker.io/directxman12/k8s-prometheus-adapter ...
> advanced-config: Pulling from docker.io/directxman12/k8s-prometheus-adapter
> f70adabe43c0: Pull complete
> f8bf1af87e51: Pull complete
> Digest: sha256:6b181b932e653b3d3b5d348db65dab636be65b0cf389d1e7e5d3f574d767a218
> v0.1.0-centos: Pulling from docker.io/directxman12/k8s-prometheus-adapter
> 74f0853ba93b: Pull complete
> 3a0de6ae89dd: Pull complete
> Digest: sha256:a891a4d4e70e83e2664b1c60fdfc19bf3f94793b497342c81169a845d3412927
> v0.1.0: Pulling from docker.io/directxman12/k8s-prometheus-adapter
> Digest: sha256:a891a4d4e70e83e2664b1c60fdfc19bf3f94793b497342c81169a845d3412927

My understanding from my recent experiments is that the images tagged 'v0.1.0-centos' and 'v0.1.0' will work for Kubernetes 1.7 and 'advanced-config' will work with 1.8 and above. See issue #66 for more details.

@DirectXMan12 Is my understanding correct? Also, do you see any issues with using the v0.1.0 image as is on a production cluster?

**Comment by DirectXMan12** [comment]
Only v0.1.0 will work with Kubernetes 1.7, correct.  v0.2.0 and up (including the soon-to-be-merged advanced config branch) work with Kubernetes 1.8+.

As for using v0.1.0 on a production cluster, there's not any serious issues that I recall.
