### ISSUE TITLE
external.metrics.k8s.io api is  FailedDiscoveryCheck

### ISSUE THREAD

**Issue by cuisongliu** [kubernetes-sigs/prometheus-adapter#365]
k8s version :

```
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl describe apiservice v1beta1.external.metrics.k8s.io
Name:         v1beta1.external.metrics.k8s.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2021-01-06T02:46:38Z
  Resource Version:    25064367
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.external.metrics.k8s.io
  UID:                 c61f8f06-a8b6-482f-9a2d-1cd9d7e7e7c6
Spec:
  Group:                     external.metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            custom-metrics-apiserver
    Namespace:       kube-system
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2021-01-26T07:27:53Z
    Message:               failing or missing response from https://172.20.93.50:6443/apis/external.metrics.k8s.io/v1beta1: bad status from https://172.20.93.50:6443/apis/external.metrics.k8s.io/v1beta1: 404
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

k8s version is too lower ?

**Comment by dgrisonnet** [comment]
I don't think that's the problem here, prometheus-adapter should work correctly in Kubernetes 1.16.

The error message seems to indicate that prometheus-adapter returned 404 NotFound when querying the external metrics endpoint, which happens whenever prometheus-adapter couldn't get any metrics. Could you please verify that you have at least one external metrics rule defined in your prometheus-adapter configuration?

**Comment by yanc0** [comment]
Thanks, It worked !

I added a dummy external rules in my adapter config and now API is discovered !

**Comment by cuisongliu** [comment]
> I don't think that's the problem here, prometheus-adapter should work correctly in Kubernetes 1.16.
> 
> The error message seems to indicate that prometheus-adapter returned 404 NotFound when querying the external metrics endpoint, which happens whenever prometheus-adapter couldn't get any metrics. Could you please verify that you have at least one external metrics rule defined in your prometheus-adapter configuration?

yes, I not add the external metrics rule to my prometheus-adapter configuration .thanks
