### ISSUE TITLE
Can't populate Resource metrics via Prometheus Adapter

### ISSUE THREAD

**Issue by KhvalIvanl** [kubernetes-sigs/prometheus-adapter#368]
Trying to get rid of metrics server to serve both custom and resource metrics by Prometheus Adapter only.

I am using a Prometheus Adapter config map with ResourceRules from this [example](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-config-map.yaml#L73-L98) and registered a new APIService for metrics.k8s.io endpoint. Once I try to test it via `kubectl top pods -n monitoring` I receive **Metrics not available for pod** error message and  **unable to fetch CPU metrics for pod** error in Adapter logs:
```log
I0207 15:59:53.986909       1 api.go:74] GET http://prometheus-service.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28container_memory_working_set_bytes%7Bnamespace%3D%22monitoring%22%2Cpod_name%3D~%22prometheus-adapter-6f7d7c45f4-t9j2f%7Cprometheus-operator-6979cdfc46-xsqdb%7Cprometheus-prometheus-0%22%7D%29+by+%28pod_name%2Ccontainer_name%29&time=1612713593.985 200 OK
I0207 15:59:53.986974       1 api.go:93] Response Body: {"status":"success","data":{"resultType":"vector","result":[]}}
I0207 15:59:53.987915       1 api.go:74] GET http://prometheus-service.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28rate%28container_cpu_usage_seconds_total%7Bnamespace%3D%22monitoring%22%2Cpod_name%3D~%22prometheus-adapter-6f7d7c45f4-t9j2f%7Cprometheus-operator-6979cdfc46-xsqdb%7Cprometheus-prometheus-0%22%7D%5B1m%5D%29%29+by+%28pod_name%2Ccontainer_name%29&time=1612713593.985 200 OK
I0207 15:59:53.988023       1 api.go:93] Response Body: {"status":"success","data":{"resultType":"vector","result":[]}}
E0207 15:59:53.988074       1 provider.go:187] unable to fetch CPU metrics for pod monitoring/prometheus-adapter-6f7d7c45f4-t9j2f, skipping
E0207 15:59:53.988083       1 provider.go:187] unable to fetch CPU metrics for pod monitoring/prometheus-operator-6979cdfc46-xsqdb, skipping
E0207 15:59:53.988090       1 provider.go:187] unable to fetch CPU metrics for pod monitoring/prometheus-prometheus-0, skipping
```
`kubectl get --raw "/apis/metrics.k8s.io/v1beta1/pods"` provides an empty API list:
```yaml
{
  "kind": "PodMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": []
}
```
At the same time custom metrics are populated as expected. Prometheus Adapter v0.8.3.

**Comment by dgrisonnet** [comment]
Could you perhaps check if the `container_cpu_usage_seconds_total` and `container_memory_working_set_bytes` metrics are reported for these containers in your Prometheus instance? If not, that would mean that your Prometheus instance doesn't scrape the metrics coming from kubelet.

**Comment by KhvalIvanl** [comment]
Oh, yes, you are right - I have fixed my ServiceMonitor and the issue is gone.

But now I have another problem: data returned by kubelet is not consistent and sometimes resource metrics from various pods are not fetched:
```
I0208 17:15:13.968182       1 api.go:74] GET http://prometheus-service.monitoring.svc.cluster.local:9090/api/v1/query?query=sum%28rate%28container_cpu_usage_seconds_total%7Bnamespace%3D%22test-namespace%22%2Cpod%3D~%22load-generator%7Cphp-apache-79544c9bd9-4d5rw%7Cphp-apache-79544c9bd9-685bm%7Cphp-apache-79544c9bd9-76mbt%7Cphp-apache-79544c9bd9-7p554%7Cphp-apache-79544c9bd9-bq96l%7Cphp-apache-79544c9bd9-cnmht%7Cphp-apache-79544c9bd9-dfhrp%7Cphp-apache-79544c9bd9-jlb8q%7Cphp-apache-79544c9bd9-lq8tm%7Cphp-apache-79544c9bd9-qspb%22%7D%5B1m%5D%29%29+by+%28pod%2Ccontainer_name%29&time=1612804513.965 200 OK
...
E0208 17:15:13.969030       1 provider.go:187] unable to fetch CPU metrics for pod test-namespace/php-apache-79544c9bd9-76mbt, skipping
E0208 17:15:13.969040       1 provider.go:187] unable to fetch CPU metrics for pod test-namespace/php-apache-79544c9bd9-7p554, skipping
E0208 17:15:13.969050       1 provider.go:187] unable to fetch CPU metrics for pod test-namespace/php-apache-79544c9bd9-cnmht, skipping
```
On the next request the list of failed pods could be different. Or all of them could be successful.

**Comment by dgrisonnet** [comment]
It might be because in the example the `pod_name` label is matched to the pod resource. However, since Kurbernetes 1.16 the `pod_name` label was renamed to `pod`: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#removed-metrics

Hence if you are using a newer version of Kubernetes, you should update the example and change to `pod` here: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-config-map.yaml#L95-L96. Same apply to the other rules.

On a side note, since you are using prometheus-operator, you could be interrested in kube-prometheus where there are more up to date example on how to configure prometheus-adapter: https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/prometheus-adapter-configMap.yaml

That being, if you are interested in contributing to prometheus-adapter, you're very welcome to do so and update the examples so that other users don't encounter the same hardships :slightly_smiling_face:.

**Comment by KhvalIvanl** [comment]
@dgrisonnet got it! Thank you for your help :).
