### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by paulfantom** [kubernetes-sigs/prometheus-adapter#371]
It would be good to have a new release of the project after it was migrated to kubernetes org. This would solve issues reported by golang when trying to import, like this one:
```
        github.com/kubernetes-sigs/prometheus-adapter/pkg/config: github.com/kubernetes-sigs/prometheus-adapter@v0.8.3: parsing go.mod:
        module declares its path as: github.com/directxman12/k8s-prometheus-adapter
                but was required as: github.com/kubernetes-sigs/prometheus-adapter
```

I am aware this can be worked around by using `replace` in go.mod, but this is only a workaround.

**Comment by dgrisonnet** [comment]
Agreed, we should do a release once we migrate all the imports from `github.com/directxman12/k8s-prometheus-adapter` to `github.com/kubernetes-sigs/prometheus-adapter`.

/help

**Comment by dgrisonnet** [comment]
I just cut release `v0.8.4` which includes the imports migration.
