### ISSUE TITLE
why i request rest-api, returned requeslt for item value has 'm' unit!!

### ISSUE THREAD

**Issue by xianglujun** [kubernetes-sigs/prometheus-adapter#376]
hello, i am using prometheus-adapter for customed metrics, but when i combine multi metric in metricQuery, i alway get returned result for item vlaue that always has 'm' unit. my configuration is followed:
`seriesQuery: '{__name__=~"^container_.*",namespace!="",pod_name!="",container=""}'
      seriesFilters: []
      resources:
        overrides:
          namespace:
            resource: namespace
          pod_name:
            resource: pod
      name:
        matches: ^container_(.*)_working_set_bytes$
        as: ""
      metricsQuery: sum(container_memory_working_set_bytes{container="",<<.LabelMatchers>>}) by (<<.GroupBy>>)/1024/1024`

returned result is followed:
`{
      "describedObject": {
        "kind": "Pod",
        "namespace": "default",
        "name": "ds-filebeat-tbfbt",
        "apiVersion": "/v1"
      },
      "metricName": "memory",
      "timestamp": "2021-02-24T10:58:34Z",
      "value": "716769m"
    }
`
> i am sure metric in prometheus returned result has no unit, because it it bytes usage for memory.

**Comment by fredr** [comment]
The `m`-suffix means milli, Quantity Values are explained here: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md#quantity-values

**Comment by xianglujun** [comment]
thanks!
