### ISSUE TITLE
+Inf metrics being converted to 0

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes-sigs/prometheus-adapter#394]
First off I'm running an old version:  directxman12/k8s-prometheus-adapter-amd64:v0.5.0
unfortunately there's an infrastructure issue we're waiting to be resolved (sometime hopefully next week) which prevents update.

We use the kafka-lag-exporter (https://github.com/lightbend/kafka-lag-exporter) which for one of their metrics typically is a number but can on occassion become '+Inf'.  The adapter appears to be converting this into a 0.  Or at least the HPA we use which points to this metric is reading a 0 when prometheus is showing +Inf.  

Is there anything we can do to resolve this, or is this an issue that will need a code fix?

Thanks

**Comment by dgrisonnet** [comment]
Hi @ryan-dyer-sp, could you please try to verify that metrics reported by prometheus-adapter are converted to 0? You can do that by following this doc: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md#double-checking-your-work.
If the adapter is indeed converting the value and it's not the HPA that does it, we will need to investigate what would be the impact of sending `+Inf` to the HPA as prometheus-adapter should reflect what is stored by Prometheus.
