### ISSUE TITLE
Can the replica of prometheus-adapter be set more than 1

### ISSUE THREAD

**Issue by swimablefish** [kubernetes-sigs/prometheus-adapter#397]
Hi, as title, can I increase the replica of prometheus-adapter to provide high availability?

**Comment by dgrisonnet** [comment]
Yes, you can and I would advise you to do so if you are running in an infrastructure that has more than one node. I've recently contributed making prometheus-adapter configuration highly available in kube-prometheus if you want to have a look at some of the manifests:

https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-adapter-deployment.yaml
https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-adapter-podDisruptionBudget.yaml

I would also recommend having hard pod anti-affinity on hostname if you are running in an environment with multiple nodes.

**Comment by swimablefish** [comment]
Great, thanks
