### ISSUE TITLE
stdout the logs of prometheus-adapter in json format

### ISSUE THREAD

**Issue by navathag** [kubernetes-sigs/prometheus-adapter#411]
how to stdout the logs of prometheus-adapter in json format

**Comment by dgrisonnet** [comment]
This is not possible yet, but it would be a good addition to the project. Although, this will require quite a lot of changes since we would need to rework prometheus-adapter's logging to use [structured logging](https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/).
