### ISSUE TITLE
Update deployment manifests and instructions

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-sigs/prometheus-adapter#426]
Deployment manifests and instructions are very outdated in the project since the community has been solely updating the kube-prometheus manifests. It would be great to leverage the efforts that were made there and update the manifests that we have in this repository.

**Comment by championshuttler** [comment]
@dgrisonnet, can you help me with getting started what i need to do? thanks

**Comment by dgrisonnet** [comment]
Sure, so the goal of this issue is to update the deployment manifests and instructions that we have in this repository under the [deploy](https://github.com/kubernetes-sigs/prometheus-adapter/tree/master/deploy) directory based on the more up-to-date manifests in kube-prometheus that are prefixed by `prometheus-adapter-` in the [manifests](https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests) directory.

The few pointers that I could give you are that you should be able to update all the manifests and bring the new ones except for the [configmap](https://github.com/kubernetes-sigs/prometheus-adapter/blob/89425b72ccd2124af3ed898bd07bf6eee50e02a5/deploy/manifests/custom-metrics-config-map.yaml) and the [apiservices](https://github.com/kubernetes-sigs/prometheus-adapter/blob/89425b72ccd2124af3ed898bd07bf6eee50e02a5/deploy/manifests/custom-metrics-apiservice.yaml) that we can keep as is, except for a few selectors that might need to be updated to match the new changes.
Also, it would be great to move away from the `custom-metrics-apiserver` resource name to `prometheus-adapter` which is used in kube-prometheus and is in my opinion more clear.
As for the deployment [instructions](https://github.com/kubernetes-sigs/prometheus-adapter/tree/89425b72ccd2124af3ed898bd07bf6eee50e02a5/deploy#example-deployment), we could move the second point out of the default deployment and add a new section explaining how users can configure the adapter and enable HTTPS.

Let me know if you need any additional information and feel free to reach out to me on slack if you need any help :slightly_smiling_face:

**Comment by dgrisonnet** [comment]
This was fixed by https://github.com/kubernetes-sigs/prometheus-adapter/pull/531.
