### ISSUE TITLE
Generate deployment manifests from jsonnet 

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-sigs/prometheus-adapter#427]
Since most of the projects in the kube-prometheus ecosystem are using jsonnet to generate their manifests, it would be great to do the same in prometheus-adapter.

We could bring the [prometheus-adapter.libsonnet](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/prometheus-adapter.libsonnet) file from kube-prometheus here and include it in kube-prometheus. This would require the kube-prometheus contributors to make the changes in this repository which would benefit the ecosystem as a whole. This way we would avoid going into the state we are in where the configuration from this repository drifted from the more up-to-date one in kube-prometheus.

**Comment by jayesh-srivastava** [comment]
Hi. I am a new contributor and I would like to work on this issue. Can you please guide me through this and assign me the issue?

**Comment by dgrisonnet** [comment]
Hi @jayesh-srivastava, sorry for the delay. Sure, if you are still interested in working on this issue, I can guide you.

What we want to do here is to have manifests generated from [jsonnet](https://jsonnet.org/). In kube-prometheus, the prometheus-adapter manifests are already generated from this [jsonnet library](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/prometheus-adapter.libsonnet). The goal would be to move this file in the project and add some tooling to generate YAML manifests.

If you are not yet familiar with Jsonnet, I would advise having a look at the tutorial on their website as well as looking into how we leverage jsonnet to customize a monitoring stack in kube-prometheus: https://github.com/dgrisonnet/kube-prometheus#customizing-kube-prometheus

The generation should work the following way:
- Add library: https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/prometheus-adapter.libsonnet
- Import library in a `.jsonnet` file: https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet#L8
- In the same jsonnet file split the different Kubernetes resources inside of the PrometheusAdapter jsonnet object into different files: https://github.com/prometheus-operator/kube-prometheus/blob/main/example.jsonnet#L34
- Lastly, generate yaml manifests by running [build.sh](https://github.com/prometheus-operator/kube-prometheus/blob/main/build.sh) $jsonnet_file

**Comment by jayesh-srivastava** [comment]
Hey @dgrisonnet Thank you for the guidance. I see this issue is closed. So probably I can't work on this right?

**Comment by dgrisonnet** [comment]
This issue is still opened, I closed a duplicate. If you want to work on this feel free to assign this issue to yourself by commenting `/assign`.

**Comment by jayesh-srivastava** [comment]
Ok thank you much.
