### ISSUE TITLE
Add jsonnet configuration files

### ISSUE THREAD

**Issue by fpetkovski** [kubernetes-sigs/prometheus-adapter#433]
Jsonnet configuration for the prometheus adapter is currently managed in [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus). Do we want to migrate the bulk of it to this repository and simply import it in kube-prometheus instead?

**Comment by dgrisonnet** [comment]
Yes, that's the direction we want to go with in kube-prometheus. This effort is currently tracked in 2 different tasks, one to first update the manifests and deployment instructions and then an effort to migrate to jsonnet and generate the manifests:

- #426 
- #427

**Comment by fpetkovski** [comment]
Closing as duplicate
