### ISSUE TITLE
Unable to connect to prometheus with username and password

### ISSUE THREAD

**Issue by visrey** [kubernetes-sigs/prometheus-adapter#439]
I have recently added basic auth of username and password for my prometheus instance and after that adapter has issues while connecting to prometheus instance.

I have tried using the `prometheus-auth-config` parameter with `--prometheus-use-auth=true`, It gives me unknown flag.

**Comment by fpetkovski** [comment]
Hello :wave:, have you tried using the latest version of the prometheus adapter?

**Comment by visrey** [comment]
Hi @fpetkovski 

Yes we tried with the latest version of prometheus adapter.
**Steps we followed:**

1. We have a working environment where prometheus and prometheus adapter are in the same cluster.
2. We have added basic authentication to prometheus with a username and password.
3. After the auth changes prometheus adapter failed to get the metrics.
4. After digging through code we found few parameter and tried them.
5. I have configured two command line parameters `--prometheus-auth-config` and `--prometheus-auth-incluster`
6. We have created a config file as below:

`
apiVersion: v1
clusters:
- name: prom
  cluster:
    server: http://prometheus:9090
contexts:
- name: prom-context
  context:
    cluster: prom
    user: prom-user
current-context: prom-context
users:
- name: prom-user
  user:
    username: admin
    password: password123
`

After all these still I am not able to get it working. 
Are we missing something ?

**Comment by fpetkovski** [comment]
Ok understood. There is no explicit way to configure basic auth, but you can specify the prometheus headers with `--prometheus-header`: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/cmd/adapter/adapter.go#L139

**Comment by visrey** [comment]
Thanks @fpetkovski 
Will give it a try and post an update

**Comment by visrey** [comment]
Hi @fpetkovski 
I think the changes you were pointing were committed 25 days back but the current release was on march 31 so we don't have the support currently. 
Is there any release planned to push this change ?

Thanks

**Comment by fpetkovski** [comment]
We haven't published a new release yet, but you can use the latest tag from the staging registry: https://console.cloud.google.com/gcr/images/k8s-staging-prometheus-adapter/GLOBAL/prometheus-adapter?gcrImageListsize=30

It corresponds to the current HEAD in master.

**Comment by szediktam** [comment]
> Ok understood. There is no explicit way to configure basic auth, but you can specify the prometheus headers with `--prometheus-header`: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/cmd/adapter/adapter.go#L139
> 
> Basic auth is just base64 encoded username:password passed over the `Authorization` header.

how to set the `Authorization` header？
--prometheus-header="Authorization=Basic aGhoOmhoaA==" ?

**Comment by data-dude** [comment]
> > Ok understood. There is no explicit way to configure basic auth, but you can specify the prometheus headers with `--prometheus-header`: https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/cmd/adapter/adapter.go#L139
> > Basic auth is just base64 encoded username:password passed over the `Authorization` header.
> 
> how to set the `Authorization` header？ `--prometheus-header="Authorization=Basic aGhoOmhoaA=="` ?
> 
> `--prometheus-header=Authorization=Basic aGhoOmhoaA==` works. thanks

Anybody get this to work as a Kubernetes deployment?  I'm not able to it doesn't like under args
 `--prometheus-header=Authorization=Basic aGhoOmhoaA==`

**Comment by data-dude** [comment]
I think i'm running into issues not having a cacert.  Is there a way to ignore verify server cert issues?

**Comment by lucasfcnunes** [comment]
Is there a way to pass the header secret via env var?
*It's for security reasons.
