### ISSUE TITLE
README.md :: Installation :: What if I'm not using helm

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes-sigs/prometheus-adapter#452]
Installation section says:

> If you're a helm user, a helm chart is listed on prometheus-community repository as prometheus-community/prometheus-adapter.

but gives no additional details about how to install if not using helm. Please add a note on how to install without helm.

**Comment by michaelfavia** [comment]
@sgpinkus you can use the helm cli tool (`helm template`) to output regular YAML if you'd like and then just k apply the files it generates. I'd add that now that helm3 doesnt require Tiller its a great solution for managing things like this and ingress controllers, etc. 

Good luck :)
