### ISSUE TITLE
Exposing Internal ("self") metrics

### ISSUE THREAD

**Issue by ankitpatel96** [kubernetes-sigs/prometheus-adapter#458]
Hi,
Is there any access to internal metrics on prometheus-adapter>  From what I can see the client registers a prometheus registry at https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/pkg/client/metrics/metrics.go - but I can't find anywhere that this is exposed over http (or any docs on the topic).

Thanks for the project by the way - its been very useful for us.

Thanks, 
- Ankit

**Comment by prashbnair** [comment]
It is exposed on the same endpoint as the one used to serve the metrics API to the api server.
You can take a look at this for your reference
https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-apiserver-service.yaml#L9

**Comment by ankitpatel96** [comment]
Thanks for the reply Prashant - but the issue is I don't really know how to access this?  If I simply add it to my scrape targets and scrape it at port 6443/metrics Prometheus complains of "server returned HTTP status 400 Bad Request".  If I try to curl "/metrics" from another pod or by port-forwarding the pod to my machine I get:
`{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
"reason": "Forbidden",
"details": {},
"code": 403
}`

This implies to me that the path is trying to authenticate as if it is an api server endpoint.  

1) Is this even the right path to curl?  As previously mentioned, I don't know what the right path is - nor is it mentioned anywhere.

2) Is there a way to auth to this endpoint that I'm not aware of?

**Comment by ankitpatel96** [comment]
I'm really sorry for dropping this thread - this problem still very much exists but I just missed the update lol.

Prometheus is bound to this clusterrole via a clusterrolebinding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"prometheus","role":"server"},"name":"prometheus"},"rules":[{"apiGroups":[""],"resources":["nodes","nodes/proxy","nodes/metrics","services","endpoints","pods","ingresses","configmaps"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","update","patch"]},{"apiGroups":["extensions"],"resources":["ingresses/status","ingresses"],"verbs":["get","list","watch"]},{"nonResourceURLs":["/metrics"],"verbs":["get"]}]}
  creationTimestamp: "2021-10-12T22:06:52Z"
  labels:
    app: prometheus
    role: server
  name: prometheus
  resourceVersion: "355588"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus
  uid: 5121f736-7954-4ec6-94bd-870006150e38
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```

**Comment by prashbnair** [comment]
This looks fine, do you have any settings in the deployment of the prometheus-adapter which sets any additional requirements?

**Comment by lli-hiya** [comment]
I managed to figure this out. Here is my solution.

I created a ServiceMonitor and under its spec/endpoints I have something like this 
```
  endpoints:
    - port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
```
, which tells prometheus to pull metrics using the service account bearer token through an https endpoint.

and this is my service definition

```
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-apiserver
  labels:
    app: custom-metrics-server
spec:
  ports:
  - port: 443
    name: https
    targetPort: 6443
  selector:
   app: custom-metrics-server
```
