### ISSUE TITLE
Upgrade APIService manifests to apiVersion: apiregistration.k8s.io/v1

### ISSUE THREAD

**Issue by cskarby** [kubernetes-sigs/prometheus-adapter#474]
https://github.com/kubernetes-sigs/prometheus-adapter/blob/c9e69613d3e1ccf4a5828aba25de613d84694779/deploy/manifests/custom-metrics-apiservice.yaml#L1 is not working with kubernetes v1.22+

The apiregistration.k8s.io/v1beta1 API version of APIService is no longer served as of v1.22.

* Migrate manifests and API clients to use the apiregistration.k8s.io/v1 API version, available since v1.10.
* No notable changes

See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

**Comment by noskywalker** [comment]
i see ,and i have changed into v1.
but why dont'you change the original yaml file?

**Comment by grzesuav** [comment]
https://github.com/kubernetes-sigs/prometheus-adapter/pull/494
