### ISSUE TITLE
documentation could be a lot more clear on how to do some of the things/flags/configuration mentioned

### ISSUE THREAD

**Issue by tommyjcarpenter** [kubernetes-sigs/prometheus-adapter#489]
A few examples:

```
The adapter takes the standard Kubernetes generic API server arguments
--prometheus-url=<url>: This is the URL used to connect to Prometheus. It will eventually contain query parameters to configure the connection.
```

took me some googling to understand *how/where* to do this.. where do I supply said argument? 
I finally found https://gist.github.com/superseb/4147cbbe432d11b63e3a4432d12df2b7
which has the secret, that you don't put --prometheus-url but rather a "set" command in helm: 
```
helm install --name prometheus-adapter stable/prometheus-adapter --set prometheus.url="http://mon-prometheus-operator-prometheus.monitoring.svc",prometheus.port="9090" --set image.tag="v0.4.1" --set rbac.create="true" --namespace kube-system 
```
This example would be very helpful. 

Another example:
```
Next, try using the --v=6 flag on the adapter to see the exact queries being made by the adapter. Try url-decoding the query and pasting it into the Prometheus web console to see if the query looks wrong.
```
how? where do I put this --v=6 flag? etc

**Comment by tommyjcarpenter** [comment]
not a bug, just a suggestion, there was no "question/suggestion" tag.

**Comment by dgrisonnet** [comment]
This repository doesn't support installing prometheus-adapter via helm so it is intended that the documentation only explains how to install prometheus-adapter via yaml manifests.

With that being said, https://github.com/prometheus-community/helm-charts might be a better place to host such documentation.

/close

**Comment by tommyjcarpenter** [comment]
@dgrisonnet I don't understand though, the very first instructions in the Readme is a helm install command!

**Comment by tommyjcarpenter** [comment]
Agree you should remove it then, because it's not Just "in" the Readme but rather the very first command the user sees under installation. So the Readme does not jive at all with this thread.
