### ISSUE TITLE
container image path is wrong (/menifates/customer-metrics-apiserver-deplpyment.yaml)

### ISSUE THREAD

**Issue by kiwonl** [kubernetes-sigs/prometheus-adapter#501]
**What happened?**:

I tried to install according the [Example Deployment](https://github.com/kubernetes-sigs/prometheus-adapter/blob/9008b12a0173e2604e794c1614081b63c17e0340/deploy/README.md). But I think that the container image path of [custom-metrics-apiserver](https://github.com/kubernetes-sigs/prometheus-adapter/blob/9008b12a0173e2604e794c1614081b63c17e0340/deploy/manifests/custom-metrics-apiserver-deployment.yaml) is wrong.
```
    spec:
      containers:
      - name: custom-metrics-apiserver
        image: gcr.io/k8s-staging-prometheus-adapter-amd64
```
Because I can't pull the image.

```
$ docker pull gcr.io/k8s-staging-prometheus-adapter-amd64
Using default tag: latest
Error response from daemon: Head "https://gcr.io/v2/k8s-staging-prometheus-adapter-amd64/manifests/latest": unknown: Invalid repository name: gcr.io/k8s-staging-prometheus-adapter-amd64
```

**Comment by StephanSalas** [comment]
Bump. This seems actually incorrect.

**Comment by olivierlemasle** [comment]
@StephanSalas The example manifest has already been updated.
It currently uses image `registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0`:

https://github.com/kubernetes-sigs/prometheus-adapter/blob/b03cc3e7c8f229eec27dc6e91f92994cd293b295/deploy/manifests/deployment.yaml#L37
