### ISSUE TITLE
Error starting container: Unknown flag: --logtostderr

### ISSUE THREAD

**Issue by shpml** [kubernetes-sigs/prometheus-adapter#525]
**What happened?**:
On Aug 12th AEST my prometheus adapter pod was gracefully terminated. 
```
"timestamp": "2022-08-11T17:47:01.987570641Z",
"message": "\"[graceful-termination] shutdown event\" name=\"ShutdownInitiated\""
```

This resulted in a pod restart and kubernetes pulling the latest image.
```
"timestamp": "2022-08-11T17:48:01Z",
"message": "Successfully pulled image \"gcr.io/k8s-staging-prometheus-adapter/prometheus-adapter-amd64:master\" in 57.551120744s",
```

This resulted in a `"CrashLoopBackOff"` event due to the following error
```
"timestamp": "2022-08-11T17:48:01.241961584Z",
"textPayload": "unknown flag: --logtostderr",
```

Unfortunately I did not have monitoring on this cluster so I missed the errors for a number of days :(.
The pod with the issue was deleted on Aug 16th AEST and a new pod successfully started after pulling the latest image 
```
"timestamp": "2022-08-16T12:14:06Z",
"message": "Successfully pulled image \"gcr.io/k8s-staging-prometheus-adapter/prometheus-adapter-amd64:master\" in 7.038956364s"
```

The container successfully started.
```
"timestamp": "2022-08-16T12:14:06Z",
"message": "Started container custom-metrics-apiserver",
```

**What did you expect to happen?**:
I expected a new pod to start without an error relating to flag `logtostderr`. 

**Please provide the prometheus-adapter config**:
The config is the default used in [deploy/manifests/custom-metrics-apiserver-deployment.yaml](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/deploy/manifests/custom-metrics-apiserver-deployment.yaml )
https://github.com/kubernetes-sigs/prometheus-adapter/blob/f23e67113ab782980a42df8b9484795f2192e64f/deploy/manifests/custom-metrics-apiserver-deployment.yaml#L31

**Anything else we need to know?**:
I don't think it's still a bug as the latest version is running but it would be good to know what happened. 

**Environment**:
- prometheus-adapter version: `gcr.io/k8s-staging-prometheus-adapter/prometheus-adapter-amd64:master`
- prometheus version: `gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0`
- Kubernetes version: `v1.21.x-gke` and `v1.22.10-gke.600`
- Cloud provider: `GKE`

**Comment by olivierlemasle** [comment]
There was visibly a regression, which was fixed in #524.
