### ISSUE TITLE
Add kubelet ServiceMonitor configuration to the walkthrough

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-sigs/prometheus-adapter#552]
The [walkthough of prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md) provides an explanation on how to deploy the default configuration of prometheus-adapter, but it doesn't explain that a ServiceMonitor for the kubelet is required to be deploy in order to be able to get pod/node resource usage. It would be great to add a section providing a very simple ServiceMonitor configuration for that.

**Comment by Sajiyah-Salat** [comment]
I understood the issue and I am beginner. Let me know where changes needs to be made.
