### ISSUE TITLE
Docs to write config for kustomize deployment

### ISSUE THREAD

**Issue by kevjumba** [kubernetes-sigs/prometheus-adapter#556]
**What happened?**:

Is there any documentation on defining custom metrics in kustomize (the `deploy/manifests/config-map.yaml` file?

**What did you expect to happen?**:

**Please provide the prometheus-adapter config**:
<details open>
<summary>prometheus-adapter config</summary>

</details>

**Please provide the HPA resource used for autoscaling**:
<details open>
<summary>HPA yaml</summary>

</details>

**Please provide the HPA status**:

**Please provide the prometheus-adapter logs with -v=6 around the time the issue happened**:
<details open>
<summary>prometheus-adapter logs</summary>

</details>

**Anything else we need to know?**:

**Environment**:
- prometheus-adapter version: 
- prometheus version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

**Comment by kevjumba** [comment]
@olivierlemasle any recommendations on how to write the config.yaml for a prometheus metric(details as follows)?
The metric is `concurrent_requests` with a few labels that I would like to set to find the specific one dimension that I'm interested in and I want to run a time series query on it that either uses rate or increase.

When I curl my endpoint using `query?` instead of `series?` I get numerical data? However, the endpoint only generates series URL get requests and when I copy the same generated query with a series? I get returned data but it's just the labels and name of the metric but no actual numerical data...

**Comment by dgrisonnet** [comment]
@kevjumba I would recommend having a look at https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config-walkthrough.md, it explains how to configure prometheus-adapter to add new custom metrics.

> When I curl my endpoint using query? instead of series? I get numerical data? However, the endpoint only generates series URL get requests and when I copy the same generated query with a series? I get returned data but it's just the labels and name of the metric but no actual numerical data...

I am not sure I understand your question here, `query` and `series` are Prometheus endpoints no?

**Comment by dashpole** [comment]
Feel free to reopen if this is still relevant

/close
