### ISSUE TITLE
uninstall prometheus-adapter

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/prometheus-adapter#557]
**What happened?**:
We have uninstalled the prometheus adapter in a cluster. Now we get error messages like this:
````
E0125 12:04:01.326930      32 memcache.go:255] couldn't get resource list for [external.metrics.k8s.io/v1beta1](http://external.metrics.k8s.io/v1beta1): Got empty response for: [external.metrics.k8s.io/v1beta1](http://external.metrics.k8s.io/v1beta1) schauen
````

**What did you expect to happen?**:

Uninstall of the helm chart should remove it from the system.

**Anything else we need to know?**:

I would just like to know how to purge prometheus-adapter from a given cluster.

**Environment**:
- prometheus-adapter version:  na
- prometheus version:  na
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: AWS EKS
- Other info:

**Comment by olivierlemasle** [comment]
Hi @runningman84,

Could you please confirm that `kubectl get apiservices v1beta1.external.metrics.k8s.io` returns a NotFound error?

I suppose the error message you mention is in the API server logs? Did you try to restart the API server after uninstalling prometheus-adapter?

I guess it is related to https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/146

**Comment by olivierlemasle** [comment]
Your last comment shows that `v1beta1.external.metrics.k8s.io` is provided by KEDA, not by prometheus-adapter. Could you please give a little more information on your issue?

The log message in your first comment does not show if the error refers to KEDA or prometheus-adapter.

/kind support
/triage accepted
/assign
