### ISSUE TITLE
Custom Metrics not getting to Kubernetes 

### ISSUE THREAD

**Issue by arunlinux18** [kubernetes-sigs/prometheus-adapter#571]
Hi
I am trying to learn custom metrics to scale deployment from @asksven envoy learning

![Ingress](https://user-images.githubusercontent.com/16564092/226626898-fe6d2142-735e-4fbe-ad5a-a1a970289ce4.png)

 
 
1)    From Nginx Pod , I can see the metrics
#curl http://localhost:9901/stats/prometheus  
 

![envoy_listener_admin_main_thread_downstream_cx_active() 2](https://user-images.githubusercontent.com/16564092/226627267-31efdefb-917c-4318-9d3b-fb20defb1a39.png)
![envoy http_ di](https://user-images.githubusercontent.com/16564092/226627342-1ce0b944-c294-4112-9b02-43cd17e2312e.png)
 
2)    Installed Prometheus and I can see the metrics reported
 
sum(rate(envoy_http_downstream_cx_active{namespace="example",service="nginx-svc"}[5m])) by (service,namespace)

![unknown](https://user-images.githubusercontent.com/16564092/226627430-10bc2515-c165-4be9-87cf-52bd2c608bde.png)

 
 
3)    Installing Prometheus adapter with below values
helm upgrade -install prometheus-adapter prometheus-community/prometheus-adapter -f values_envoy.yaml -n monitor
 
 
 
Admin:~/environment $ cat values_envoy.yaml 
# values.yaml
prometheus:
  port: 80
  url: http://prometheus-server.prometheus.svc
rules:
  default: false
  resource: {}
  custom:
    - seriesQuery: '{namespace!="",service!="",envoy_http_conn_manager_prefix!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          service: {resource: "service"}
          node: {resource: "node"}
      name:
       matches: 'envoy_http_downstream_cx_total'
       as: 'http_downstream_cx_total'
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>,container!="POD"}[2m])) by (<<.GroupBy>>)'
Admin:~/environment $
 
**I tried few different metric queries but none of them have given me any clue** 
 
Admin:~/environment $ cat values_envoy.bkup 
# values.yaml
prometheus:
  port: 80
  url: http://prometheus-server.prometheus.svc
rules:
  default: false
  resource: {}
  custom:
    - seriesQuery: 'envoy_http_downstream_cx_active'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          node: {resource: "node"}
          service: {resource: "service"}
      name:
       matches: "envoy_http_downstream_cx_active"
       as: "http_downstream_cx_active"
      metricsQuery: 'sum(rate((envoy_http_downstream_cx_active{service="nginx-svc", namespace="example"}[5m]))) by (envoy_http_conn_manager_prefix)'
Admin:~/environment $
 
 
 
 
 
 
 
4)     When I try to see the metric reported on the custom API, I don’t get the metrics

 
![unknown](https://user-images.githubusercontent.com/16564092/226627545-d85b1328-edeb-432e-8d29-d0e150b17db1.png)

 
Admin:~/environment $ kubectl get apiservices |grep custom
v1beta1.custom.metrics.k8s.io          monitor/prometheus-adapter   True        36m
Admin:~/environment $

Any suggestions? why the metrics are not visible to Kubernetes.

**Comment by logicalhan** [comment]
This kind of question is best suited for stackoverflow. 
/assign @dgrisonnet

**Comment by dgrisonnet** [comment]
I don't have the time to help you debugging that, but I would recommend reading https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/walkthrough.md in order to better understand how to configure prometheus-adapter and debug it.
