### ISSUE TITLE
Guide to use basic auth for prometheus adapter to VM

### ISSUE THREAD

**Issue by Maag2510** [kubernetes-sigs/prometheus-adapter#572]
We are trying to connect prometheus adapter to external VM using basic auth but unable to to do.
We used TLS certificate headers and for authentication we tried to use args like '--prometheus-header=Authorization=Basic cHJvbWV0aGV1czpwcm9tZXRoZXVz' where cHJvbWV0aGV1czpwcm9tZXRoZXVz is Base64 value for our username:password.
While establishing connection we see errors like Bad Response, invalid character 'c'.

Please advise correct way to use basic auth in prometheus adapter.

**Comment by Maag2510** [comment]
hi @dgrisonnet , we tried the above approach but in this case getting the error like 

> net/http: invalid header field name "\"Authorization"

I also tried `--prometheus-header=Authorization "Basic cHJvbWV0aGV1czpwcm9tZXRoZXVz"` but same bad response. 
Please suggest correct way to use auth header.

**Comment by zypln** [comment]
@Maag2510 you can try with : --prometheus-header=Authorization=Basic cHJvbWV0aGV1czpwcm9tZXRoZXVz . It works normally in my environment. Note: Do not have double quotes.

**Comment by dgrisonnet** [comment]
We don't have the resources to look into this right now.
