### ISSUE TITLE
Unable to get interface metrics

### ISSUE THREAD

**Issue by Cairry** [kubernetes-sigs/prometheus-adapter#585]
I deployed the prometheus-adapter service, and pointed to my prometheus service, obtained the interface information by getting the command, could not find the data I wanted, and could not configure HPA.
`root@node1:/opt# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}`

`rules:
  default: false
  custom:
  - seriesQuery: 'nginx_vts_server_requests_total'
    resources: 
      overrides:
        kubernetes_namespace:
          resource: namespace
        kubernetes_pod_name:
          resource: pod
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))

prometheus:
  url: http://prometheus-prometheus-oper-prometheus.monitoring.svc
  port: 9090`
<img width="1917" alt="image" src="https://github.com/kubernetes-sigs/prometheus-adapter/assets/115769353/f96f92f5-21d3-4425-a0e7-2504b0c121fd">

**Comment by dgrisonnet** [comment]
We don't have enough resources right now to look into this.
