### ISSUE TITLE
When pulling arm64 image I get an amd64 one

### ISSUE THREAD

**Issue by hmonsalv** [kubernetes-sigs/prometheus-adapter#600]
**What happened?**: the docker manifest [registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.0](https://explore.ggcr.dev/?image=registry.k8s.io%2Fprometheus-adapter%2Fprometheus-adapter%3Av0.11.0) apparently has `linux/arm64` support:

```json
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 2403,
"digest": "sha256:f7a904c3c7055eff990a1b9a2177d8053a680028a323bb82ca2790f3e2d7a9d9",
"platform": {
"architecture": "arm64",
"os": "linux"
}
}
```

But when pulling `linux/arm64` image, I am getting an image with `amd64` architecture instead.
I tested it for both `v0.10.0` and `v0.11.0`:

```bash
❯ docker pull registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.0 --platform arm64
...
❯ docker image inspect registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.0 | jq -r ".[0].Architecture"
amd64
```

**What did you expect to happen?**: get the arm64 image. This is working fine for other images in same registry, e.g.:

```bash
❯ docker pull registry.k8s.io/pause:3.6 --platform arm64
...
❯ docker image inspect registry.k8s.io/pause:3.6 | jq -r ".[0].Architecture"
arm64
```

Could it be that the docker manifest reference to the `linux/arm64` is wrongly pointing to an `linux/amd64` one?

Thanks a lot in advance!
Kind regards.

**Comment by dgrisonnet** [comment]
Thank you for the report @hmonsalv, there was something wrong with the way I built the multi arch images. The PR I opened should've fixed the issue. There is currently a job in progress that will publish new staging images https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-prometheus-adapter-push-images/1694021319764480000. Once it is done and I have verified that the image have now the correct architecture, I will work on a new release of prometheus-adapter.

**Comment by hmonsalv** [comment]
Thanks Damien!
Will this new patch release be back ported to v.0.10?
When do you estimate it will be available?

**Comment by dgrisonnet** [comment]
Yes I can backport it. Either today or tomorrow

**Comment by dgrisonnet** [comment]
@hmonsalv release v0.10.1 is now available

**Comment by hmonsalv** [comment]
@dgrisonnet would it be possible to back port the fix also to v0.9 and create a `v0.9.2`? 
Thanks in advance!

**Comment by dgrisonnet** [comment]
v0.9.1 is already 2 years old which means that is using an unsupported version of Kubernetes and golang, so I'd rather have you update to v0.10.1.

**Comment by hmonsalv** [comment]
We did already for our actual cluster stack where we bumped to `v0.10.1`.
But due to some qa and compliance we still need to provide support for a few more months to our old stack where we used `v0.9.1`. It would be awesome to have the `v0.9.2` with arm64 🙏
