### ISSUE TITLE
how to aggregate query with multiple metrics  ?

### ISSUE THREAD

**Issue by omyhub** [kubernetes-sigs/prometheus-adapter#629]
aggregate query with multiple metrics , could u take more example
for example,  promsql: 
sum(jvm_memory_used_bytes{area="heap"}) by (pod) * 100.0 / sum(jvm_memory_max_bytes{area="heap"}) by (pod)
what's the rules ? 
i understand metricsQuery is a go template , but seriesQuery support promsql  completely  ?  would u give more detail  of seriesQuery ?

**Comment by dashpole** [comment]
> i understand metricsQuery is a go template , but seriesQuery support promsql completely ?

Yes, it should support promql.  This isn't the right place for questions about writing promql queries.  I would recommend reaching out through official prometheus community support channels: https://prometheus.io/community/
