### ISSUE TITLE
Adapter does not react to its config changes 

### ISSUE THREAD

**Issue by eero-t** [kubernetes-sigs/prometheus-adapter#678]
**What happened?**:

Changed prometheus-adapter (custom metrics configMap) config.

Geneated custom metrics did not change until adapter was restarted (by deleting its pod).

**What did you expect to happen?**:

Similarly to Prometheus, adapter has config-reloader to handle config changes:
```
$ kubectl -n monitoring get statefulset/prometheus-prom-kube-prometheus-stack-prometheus -o json | jq .spec.template.spec.containers[].name
"prometheus"
"config-reloader"
$ kubectl -n monitoring get deployment/prom-adapter-prometheus-adapter -o json | jq .spec.template.spec.containers[].name
"prometheus-adapter"
```

**Anything else we need to know?**:

Currently handling any automation related to custom metrics is really frustrating.  Making that reasonable would require both automatic config reloading, and some prometheus-operator support (https://github.com/prometheus-operator/kube-prometheus/issues/2504).

**Environment**:
- prometheus-adapter version: v0.12.0
- prometheus version: v2.54.0
- Kubernetes version (use `kubectl version`): 1.30

**Comment by dgrisonnet** [comment]
It is expected, prometheus-adapter doesn't support automatic config reloading.
