### ISSUE TITLE
make docker-build does not work

### ISSUE THREAD

**Issue by sreddybr3** [kubernetes-sigs/prometheus-adapter#81]
1. make docker-build is not working
2. Even if we make it work, does it work with Kubernetes 1.9 ?

**Comment by DirectXMan12** [comment]
what error does `make docker-build` give you?

**Comment by sreddybr3** [comment]
` make docker-build`
`dep ensure -vendor-only `-> takes forever and on Ctrl+C, we get the following error message:
 failed to write dep tree: failed to export bitbucket.org/ww/goautoneg: no valid source could be created:
	failed to set up sources from the following URLs:
https://bitbucket.org/ww/goautoneg
: hg is not installed:
	failed to set up source

I tried to get the dependencies directly (without docker) using `dep ensure` or ` dep ensure --update` from my mac
Warning: Gopkg.lock is out of sync with Gopkg.toml or the project's imports.
-> takes forever and no packages in vendor directory

**Comment by sreddybr3** [comment]
If we get our own docker image from the master, does it work in Kubernetes 1.9.6 ?

**Comment by DirectXMan12** [comment]
> hg is not installed: failed to set up source

That makes sense, actually, but it's weird that we didn't see it before.  I'll have to figure out how to solve it (maybe using the Kubernetes builder image?).  I don't use the `make docker-build` on a regular basis myself (making locally and using `make local-image-build` is a bit faster for me), so I must've missed that one.

> If we get our own docker image from the master, does it work in Kubernetes 1.9.6 ?

It should work with Kubernetes 1.9.  Please let me know if it does not.  The only change is that the API registration graduated to beta in 1.10, so you might have to change the `apiVersion` of the `APIService` object in the sample deployment manifests.

**Comment by sreddybr3** [comment]
@DirectXMan12 Thank you, build is successful when is use the command make docker-build VENDOR_DOCKERIZED=1

I will test it on K8S 1.9 and update the findings

**Comment by sreddybr3** [comment]
I changed apiVersion: extensions/v1beta1 of custom-metrics-apiserver-deployment.yaml 

Error 1: Error loading from default_config.yaml -> file not found
Changed - --config=/default-config.yaml to  - --config=/etc/adapter/config.yaml and error 1 is solved

Error 2: panic: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:monitoring:custom-metrics-apiserver" cannot get configmaps in the namespace "kube-system"

Kindly help.

**Comment by sreddybr3** [comment]
fixed it by adding configmaps in custom-metrics-resource-reader-cluster-role.yaml
  - services
  - configmaps


And also tested successfully in Kubernetes 1.9 and custom metrics are available:
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/dev/pods/*/accelerator_memory_used_bytes"

HPA based on custom metrics is working as expected :-)
