### ISSUE TITLE
Custom config does not work

### ISSUE THREAD

**Issue by czchen** [kubernetes-sigs/prometheus-adapter#88]
We have the following error message when trying to use image `directxman12/k8s-prometheus-adapter:advanced-config` for `HorizontalPodAutoscaler`. It looks like `metricsQuery` does not do template substitute. Any idea why?

The following is log from `custom-metrics`.

```
I0704 15:03:07.074706       1 api.go:74] GET http://prometheus.prometheus:9090/api/v1/query?query=avg%28%3C%3C.Series%3E%3E%7B%3C%3C.LabelMatchers%3E%3E%7D%29$
time=1530716587.073 400 Bad Request                                                                                                                                  
I0704 15:03:07.074767       1 api.go:93] Response Body: {"status":"error","errorType":"bad_data","error":"parse error at char 5: no valid expression found"}   
```

The following is content of `config.yaml`.

```
rules:
-   seriesQuery: '{kubernetes_namespace="namespace-name"}'
    resources:
        overrides:
            kubernetes_namespace:
                resource: namespace
            kubernetes_pod_name:
                resource: pod
    metricsQuery: avg(<<.Series>>{<<.LabelMatchers>>})

```

**Comment by DirectXMan12** [comment]
I think you're running a prototype of the advanced config image, so it's not doing the substitution.  What image version are you running?  There's some CI issues right now...

**Comment by DirectXMan12** [comment]
Ok, CI issues are fixed.  Please try again with the latest image (`directxman12/k8s-prometheus-adapter-amd64`, or whatever the appropriate suffix is for your platform).

**Comment by santinoncs** [comment]
hi!

It is very dangerous to use latest as a tag image.

:)

**Comment by DirectXMan12** [comment]
yes, I was suggesting to try that out, since I just pushed a new change.  You could always fix on a particular SHA.  I didn't want to tag a release until I was certain that things were working properly.
